Repository vuejs/vue-cli, pull requests merged in 2019-11, with the labels that each got.

#4760 Add 'Browse plugins' link to header
  docs/.vuepress/config.js
Labels: PR: Documentation

#4767 feat: support binary mirrors for taobao registry
  packages/@vue/cli/lib/util/ProjectPackageManager.js
Labels: PR: New Feature

#4532 Enforces require.resolve for loaders
  packages/@vue/babel-preset-app/package.json
  packages/@vue/cli-plugin-babel/index.js
  packages/@vue/cli-plugin-babel/package.json
  packages/@vue/cli-plugin-typescript/__tests__/tsPluginBabel.spec.js
  packages/@vue/cli-plugin-typescript/index.js
  packages/@vue/cli-plugin-typescript/package.json
  packages/@vue/cli-service/__tests__/css.spec.js
  packages/@vue/cli-service/lib/config/base.js
  packages/@vue/cli-service/lib/config/css.js
  packages/@vue/cli-service/package.json
  packages/@vue/cli-ui/index.js
Labels: PR: Bug Fix

#4777 refactor: use babel overrides to transpile babel runtime helpers
  packages/@vue/babel-preset-app/__tests__/babel-preset.spec.js
  packages/@vue/babel-preset-app/index.js
  packages/@vue/babel-preset-app/package.json
  packages/@vue/cli-plugin-babel/__tests__/babel-runtime.spec.js
  packages/@vue/cli-plugin-babel/index.js
  packages/@vue/cli-service/__tests__/serve.spec.js
Labels: PR: Bug Fix, PR: Internal

#4803 fix docs `css.loaderOptions.css.localsConvention`
  docs/guide/css.md
Labels: PR: Documentation

#4797 fix: add `sourceType: 'unambiguous'` to babel preset
  packages/@vue/babel-preset-app/__tests__/babel-preset.spec.js
  packages/@vue/babel-preset-app/index.js
Labels: PR: Bug Fix

#4798 feat: enable postcss+autoprefixer by default internally, reducing boilerplate
  .postcssrc
  packages/@vue/cli-service/__tests__/css.spec.js
  packages/@vue/cli-service/generator/index.js
  packages/@vue/cli-service/lib/config/css.js
  packages/@vue/cli-ui-addon-webpack/.postcssrc
  packages/@vue/cli-ui-addon-widgets/postcss.config.js
  packages/@vue/cli-ui/.postcssrc
  packages/@vue/cli/lib/Creator.js
Labels: PR: New Feature

#4715 feat(GeneratorAPI): accept multiple arguments for the resolve method
  docs/dev-guide/generator-api.md
  packages/@vue/cli/lib/GeneratorAPI.js
Labels: PR: New Feature

#4716 use gitlab CI env variable for project name
  docs/guide/deployment.md
Labels: PR: Documentation

#4809 fix(lib): replace "url" module with simple string split (close #4667)
  packages/@vue/cli-service/lib/commands/build/formatStats.js
Labels: PR: Bug Fix

#4816 fix: don't prepend publicPath with slash
  packages/@vue/cli-service/__tests__/Service.spec.js
  packages/@vue/cli-service/lib/Service.js
Labels: PR: Bug Fix

#4818 Add missing cli-ui dependencies
  packages/@vue/cli-ui/package.json
Labels: PR: Internal

#4736 feat: allow use of full url for pwa manifest and icons
  packages/@vue/cli-plugin-pwa/lib/HtmlPwaPlugin.js
Labels: PR: New Feature

#4836 docs: add warnings on CSS sideEffects
  docs/guide/build-targets.md
  docs/zh/guide/build-targets.md
Labels: PR: Documentation

#4859 fix: invalid version error when modules not installed
  packages/@vue/cli/lib/Upgrader.js
Labels: PR: Bug Fix

#4883 fix: support `parser` option for codemods, and enable ts parsing by default
  packages/@vue/cli/__tests__/Generator.spec.js
  packages/@vue/cli/lib/util/runCodemod.js
Labels: PR: Bug Fix

#4842 Replace chalk.reset with stripAnsi in @vue/cli-shared-utils/lib/logger.js
  packages/@vue/cli-shared-utils/lib/logger.js
  packages/@vue/cli-shared-utils/package.json
Labels: PR: Bug Fix

#4894 fix: fix tsx compilation
  packages/@vue/cli-plugin-typescript/__tests__/tsPluginBabel.spec.js
  packages/@vue/cli-plugin-typescript/index.js
Labels: PR: Bug Fix
