Repository vuejs/vue-cli, pull requests merged in 2019-04, with the labels that each got.

#3595 feat: support multi-main entry in pages config
  packages/@vue/cli-service/__tests__/multiPage.spec.js
  packages/@vue/cli-service/lib/config/app.js
  packages/@vue/cli-service/lib/options.js
Labels: PR: New Feature

#3589 feat: add jest typeahead plugin
  packages/@vue/cli-plugin-unit-jest/generator/index.js
  packages/@vue/cli-plugin-unit-jest/package.json
  yarn.lock
Labels: PR: New Feature

#3742 revert: "fix: should not add polyfills from transform-runtime plugin (#3730)"
  packages/@vue/babel-preset-app/__tests__/babel-preset.spec.js
  packages/@vue/babel-preset-app/index.js
  packages/@vue/babel-preset-app/package.json
  packages/@vue/cli-plugin-babel/index.js
Labels: PR: Bug Fix

#3628 feat: make `fibers` opt-in for dart sass
  docs/guide/css.md
  packages/@vue/cli-service/__tests__/generator.spec.js
  packages/@vue/cli-service/generator/index.js
Labels: PR: Internal

#3572 Add 3rd option to `lintOnSave` to support 'default' behaviour (fix #3552)
  docs/config/README.md
  packages/@vue/cli-plugin-eslint/index.js
  packages/@vue/cli-service/lib/options.js
Labels: PR: New Feature

#3709 chore: use high resolution version of favicon.ico
  packages/@vue/cli-service/generator/template/public/favicon.ico
Labels: PR: Internal

#3388 chore(plugin/nightwatch): bump nightwatch dependency
  packages/@vue/cli-plugin-e2e-nightwatch/package.json
Labels: PR: Breaking Change, PR: Underlying Tools

#3760 feat: bundle currentScript polyfill by default if library needs IE support
  docs/guide/build-targets.md
  packages/@vue/cli-service/lib/commands/build/resolveLibConfig.js
  packages/@vue/cli-service/lib/commands/build/setPublicPath.js
  packages/@vue/cli-service/package.json
  yarn.lock
Labels: PR: New Feature

#1531 feat: support PNPM as a package manager
  packages/@vue/cli-service/lib/commands/serve.js
  packages/@vue/cli-shared-utils/lib/env.js
  packages/@vue/cli-ui/apollo-server/type-defs.js
  packages/@vue/cli-ui/apollo-server/util/command.js
  packages/@vue/cli-ui/src/components/project-create/ProjectCreate.vue
  packages/@vue/cli/__tests__/Creator.spec.js
  packages/@vue/cli/lib/Creator.js
  packages/@vue/cli/lib/add.js
  packages/@vue/cli/lib/invoke.js
  packages/@vue/cli/lib/options.js
  packages/@vue/cli/lib/util/installDeps.js
  packages/@vue/cli/lib/util/loadCommand.js
  packages/@vue/cli/lib/util/registries.js
Labels: PR: New Feature

#3775 feat: use ESLint v5 by default everywhere
  packages/@vue/cli-plugin-eslint/generator/index.js
  packages/@vue/cli-plugin-eslint/package.json
  packages/@vue/cli-service-global/package.json
Labels: PR: Breaking Change, PR: Underlying Tools

#3774 chore: remove support for legacy `vue-cli-service e2e` command
  packages/@vue/cli-plugin-e2e-nightwatch/index.js
Labels: PR: Breaking Change

#3707 chore: more accurate vim swap file ignore
  packages/@vue/cli-service/generator/template/_gitignore
Labels: PR: Internal

#3708 Mention admin privileges as a install requirement
  docs/guide/installation.md
Labels: PR: Documentation

#3643 feat: do not write undefined fields to config files
  packages/@vue/cli/lib/util/__tests__/extendJSConfig.spec.js
  packages/@vue/cli/lib/util/extendJSConfig.js
Labels: PR: New Feature

#3778 refactor(plugin): invoke is now done in child process
  packages/@vue/cli-service/lib/PluginAPI.js
  packages/@vue/cli-ui/apollo-server/connectors/plugins.js
  packages/@vue/cli/lib/invoke.js
Labels: feat: ui

#3650 workflow: use lerna-changelog
  .gitignore
  lerna.json
  package.json
  scripts/genChangelog.js
  scripts/markVersions.js
  scripts/release.js
  yarn.lock
Labels: PR: Internal

#3754 docs: add tip about jsx options
  packages/@vue/babel-preset-app/README.md
Labels: PR: Documentation

#2405 refactor: remove unused `placeAtRootIfRelative` parameter
  packages/@vue/cli-service/lib/util/getAssetPath.js
Labels: PR: Internal

#3568 feat(cli): Added makeJSOnlyValue to generator API. Provides convenien…
  docs/dev-guide/generator-api.md
  packages/@vue/cli/__tests__/Generator.spec.js
  packages/@vue/cli/lib/GeneratorAPI.js
Labels: PR: New Feature

#3703 feat(cli-service): add --filename option to specify the output file name
  packages/@vue/cli-service/__tests__/buildLib.spec.js
  packages/@vue/cli-service/lib/commands/build/demo-lib-js.html
  packages/@vue/cli-service/lib/commands/build/demo-lib.html
  packages/@vue/cli-service/lib/commands/build/index.js
  packages/@vue/cli-service/lib/commands/build/resolveLibConfig.js
Labels: PR: New Feature

#3688 feat(ui): add copyContent to clipboard button on terminal component
  packages/@vue/cli-ui/locales/en.json
  packages/@vue/cli-ui/src/components/content/TerminalView.vue
Labels: PR: New Feature

#3790 fix pnpm compatibility issues during scaffolding
  packages/@vue/cli-service/lib/commands/serve.js
  packages/@vue/cli-shared-utils/lib/env.js
  packages/@vue/cli-ui/apollo-server/util/command.js
  packages/@vue/cli-ui/src/components/file-diff/FileDiffView.vue
  packages/@vue/cli/lib/Creator.js
  packages/@vue/cli/lib/add.js
  packages/@vue/cli/lib/invoke.js
  packages/@vue/cli/lib/util/installDeps.js
  packages/@vue/cli/lib/util/loadCommand.js
Labels: PR: Bug Fix

#3801 fix: fix ERR_INVALID_ARG_TYPE error when launching `vue ui`
  packages/@vue/cli-ui/apollo-server/util/rcFolder.js
Labels: PR: Bug Fix

#3806 fix vue add/invoke bug when user does not have yarn installed
  packages/@vue/cli-ui/apollo-server/util/command.js
  packages/@vue/cli/lib/add.js
  packages/@vue/cli/lib/invoke.js
Labels: PR: Bug Fix

#3717 Fixed progress-path background color for dark mode
  packages/@vue/cli-ui-addon-webpack/src/components/BuildProgress.vue
Labels: PR: Bug Fix, feat: ui

#3815 fix: jest typeahead config
  packages/@vue/cli-plugin-unit-jest/generator/index.js
Labels: PR: Bug Fix

#3844 feat: syntax highlight inspect output
  packages/@vue/cli-service/lib/commands/inspect.js
  packages/@vue/cli-service/package.json
  yarn.lock
Labels: PR: New Feature, enhancement, feat: cli

#3851 Remove redundant <= IE8 rule
  packages/@vue/cli-service/generator/index.js
  packages/@vue/cli-ui-addon-widgets/.browserslistrc
Labels: PR: Internal

#3782 refactor: use EnvironmentPlugin instead of DefinePlugin
  packages/@vue/cli-service/lib/commands/build/resolveWcConfig.js
  packages/@vue/cli-service/lib/config/app.js
  packages/@vue/cli-service/lib/config/base.js
  packages/@vue/cli-service/lib/util/resolveClientEnv.js
Labels: PR: Breaking Change, PR: Internal

#3852 feat!: require ESLint as a peer dependency
  packages/@vue/cli-plugin-eslint/generator/index.js
  packages/@vue/cli-plugin-eslint/index.js
  packages/@vue/cli-plugin-eslint/package.json
Labels: PR: Breaking Change

#3853 feat!: set `whitespace: 'condense'` for template compiler
  packages/@vue/cli-service/lib/config/base.js
Labels: PR: Breaking Change

#3826 fix: should not show error message when pnpm is not installed
  packages/@vue/cli-shared-utils/lib/env.js
Labels: PR: Bug Fix

#3866 feat!: upgrade css-loader to v2
  packages/@vue/cli-service/package.json
Labels: PR: Breaking Change, PR: Internal

#3870 feat!: upgrade jest to v24
  package.json
  packages/@vue/cli-plugin-typescript/package.json
  packages/@vue/cli-plugin-unit-jest/generator/index.js
  packages/@vue/cli-plugin-unit-jest/package.json
Labels: PR: Breaking Change, PR: Underlying Tools

#3871 fix: vue-virtual-scroller should be in devDependencies as it's client-side only
  packages/@vue/cli-ui/package.json
Labels: PR: Bug Fix

#3867 fix: pin jest-watch-typeahead to 0.2.1, avoid introducing jest 24 deps
  packages/@vue/cli-plugin-unit-jest/package.json
Labels: PR: Bug Fix

#3865 fix: should invalidate cache when lockfiles have updated
  packages/@vue/cli-service/lib/PluginAPI.js
Labels: PR: Bug Fix

#3878 fix: `process` should be polyfilled rather than mocked
  packages/@vue/cli-service/lib/config/base.js
Labels: PR: Internal

#3848 feat: should support `bare` option in `preset.json`
  packages/@vue/cli/lib/Creator.js
Labels: PR: New Feature

#3847 feat: add types for new `lintOnSave` options and multi-page entries
  packages/@vue/cli-service/types/ProjectOptions.d.ts
Labels: PR: New Feature

#3864 feat: allow `parallel` option to be an integer
  packages/@vue/cli-plugin-babel/index.js
  packages/@vue/cli-plugin-typescript/index.js
  packages/@vue/cli-service/lib/options.js
  packages/@vue/cli-service/types/ProjectOptions.d.ts
Labels: PR: New Feature

#3861 feat: add `.version` field and `assertVersion` helper to plugin api
  docs/dev-guide/plugin-api.md
  packages/@vue/cli-service/__tests__/Service.spec.js
  packages/@vue/cli-service/lib/PluginAPI.js
Labels: PR: New Feature

#3899 fix: should not add polyfills from transform-runtime plugin
  packages/@vue/babel-preset-app/__tests__/babel-preset.spec.js
  packages/@vue/babel-preset-app/index.js
  packages/@vue/babel-preset-app/package.json
  yarn.lock
Labels: PR: Internal

#3863 feat!: enable splitChunks by default even in development mode
  packages/@vue/cli-service/lib/config/app.js
Labels: PR: Breaking Change

#3912 feat!: upgrade to core-js 3
  packages/@vue/babel-preset-app/__tests__/babel-preset.spec.js
  packages/@vue/babel-preset-app/index.js
  packages/@vue/babel-preset-app/package.json
  packages/@vue/cli-plugin-babel/generator.js
  packages/@vue/cli-ui-addon-webpack/package.json
  packages/@vue/cli-ui-addon-widgets/package.json
  packages/@vue/cli-ui/package.json
Labels: PR: Breaking Change, PR: Underlying Tools

#3913 feat!: upgrade to webpack-chain v5
  packages/@vue/cli-service/lib/config/prod.js
  packages/@vue/cli-service/package.json
Labels: PR: Breaking Change, PR: Underlying Tools

#3914 feat!: upgrade to mocha 6 and use mochapack instead of mocha-webpack
  packages/@vue/cli-plugin-unit-mocha/index.js
  packages/@vue/cli-plugin-unit-mocha/package.json
Labels: PR: Breaking Change, PR: Underlying Tools

#3915 feat!: upgrade to workbox v4
  packages/@vue/cli-plugin-pwa/index.js
  packages/@vue/cli-plugin-pwa/package.json
Labels: PR: Breaking Change, PR: Underlying Tools

#3916 chore!: upgrade chromedriver to 74 and make it a peer dependency
  packages/@vue/cli-plugin-e2e-nightwatch/generator/index.js
  packages/@vue/cli-plugin-e2e-nightwatch/package.json
Labels: PR: Breaking Change, PR: Underlying Tools

#2981 feat!: manifest.json should be generated by cli-plugin-pwa
  packages/@vue/cli-plugin-pwa/README.md
  packages/@vue/cli-plugin-pwa/generator/template/public/manifest.json
  packages/@vue/cli-plugin-pwa/lib/HtmlPwaPlugin.js
Labels: PR: Breaking Change, PR: New Feature

#3918 chore!: upgrade to copy-webpack-plugin v5
  packages/@vue/cli-service/package.json
Labels: PR: Breaking Change, PR: Underlying Tools

#3921 chore!: default to dart sass for `sass` option of `cssPreprocessor`
  packages/@vue/cli-service/__tests__/generator.spec.js
  packages/@vue/cli-service/generator/index.js
  packages/@vue/cli/lib/options.js
  packages/@vue/cli/lib/util/inferRootOptions.js
Labels: PR: Breaking Change
