Repository vuejs/vue-cli, pull requests merged in 2019-09, with the labels that each got.

#4512 fix(pluginResolution): support dots in scope names
  packages/@vue/cli-shared-utils/__tests__/pluginResolution.spec.js
  packages/@vue/cli-shared-utils/lib/pluginResolution.js
Labels: PR: Bug Fix

#4500 Documentation typo fixes
  docs/guide/cli-service.md
  docs/guide/html-and-static-assets.md
Labels: PR: Documentation

#4497 feat: add `vue outdated` command & make `vue upgrade` interactive
  packages/@vue/cli/bin/vue.js
  packages/@vue/cli/lib/Upgrader.js
  packages/@vue/cli/lib/outdated.js
  packages/@vue/cli/lib/upgrade.js
Labels: PR: New Feature

#4533 fix(cli-plugin-babel): roperly exports the babel preset
  packages/@vue/cli-plugin-babel/generator.js
  packages/@vue/cli-plugin-babel/preset.js
  packages/@vue/cli-plugin-typescript/__tests__/tsGenerator.spec.js
Labels: PR: Bug Fix, PR: New Feature

#4445 feat: Check for `nightwatch.conf.js` config
  packages/@vue/cli-plugin-e2e-nightwatch/index.js
Labels: PR: New Feature

#4505 docs(zh): update build-targets.md
  docs/zh/guide/build-targets.md
Labels: PR: Documentation

#4546 fix(upgrade): correctly update version range in package.json
  packages/@vue/cli/__tests__/Upgrader.spec.js
  packages/@vue/cli/lib/Upgrader.js
Labels: PR: Bug Fix

#4549 feat: implement a migrator to auto add eslint to deps
  packages/@vue/cli-plugin-eslint/migrator/index.js
  packages/@vue/cli/__tests__/Upgrader.spec.js
Labels: PR: New Feature

#4550 fix: should not proxy sockjs endpoint
  packages/@vue/cli-service/lib/util/prepareProxy.js
Labels: PR: Bug Fix

#4440 fix: fix incompatibility with Chrome 75
  packages/@vue/cli-plugin-e2e-nightwatch/nightwatch.config.js
Labels: PR: Bug Fix

#4486 docs: update Chinese translation of Deployment
  docs/zh/guide/deployment.md
Labels: PR: Documentation

#4541 Upgrade Nightwatch to v1.2 and update bundled config and generated tests
  packages/@vue/cli-plugin-e2e-nightwatch/README.md
  packages/@vue/cli-plugin-e2e-nightwatch/__tests__/lib/globals-gecko.js
  packages/@vue/cli-plugin-e2e-nightwatch/__tests__/lib/globals-generated.js
  packages/@vue/cli-plugin-e2e-nightwatch/__tests__/lib/nightwatch.conf.js
  packages/@vue/cli-plugin-e2e-nightwatch/__tests__/nightwatchPlugin.spec.js
  packages/@vue/cli-plugin-e2e-nightwatch/generator/index.js
  packages/@vue/cli-plugin-e2e-nightwatch/generator/template/tests/e2e/custom-assertions/elementCount.js
  packages/@vue/cli-plugin-e2e-nightwatch/generator/template/tests/e2e/custom-commands/customExecute.js
  packages/@vue/cli-plugin-e2e-nightwatch/generator/template/tests/e2e/custom-commands/openHomepage.js
  packages/@vue/cli-plugin-e2e-nightwatch/generator/template/tests/e2e/custom-commands/openHomepageClass.js
  packages/@vue/cli-plugin-e2e-nightwatch/generator/template/tests/e2e/globals.js
  packages/@vue/cli-plugin-e2e-nightwatch/generator/template/tests/e2e/page-objects/homepage.js
  packages/@vue/cli-plugin-e2e-nightwatch/generator/template/tests/e2e/specs/test-with-pageobjects.js
  packages/@vue/cli-plugin-e2e-nightwatch/generator/template/tests/e2e/specs/test.js
  packages/@vue/cli-plugin-e2e-nightwatch/index.js
  packages/@vue/cli-plugin-e2e-nightwatch/nightwatch.config.js
  packages/@vue/cli-plugin-e2e-nightwatch/package.json
Labels: PR: New Feature

#4554 Support sass-loader v8
  docs/guide/css.md
  docs/zh/guide/css.md
  packages/@vue/cli-service/__tests__/css.spec.js
  packages/@vue/cli-service/generator/index.js
  packages/@vue/cli-service/lib/config/css.js
  packages/@vue/cli-service/package.json
  packages/@vue/cli-shared-utils/lib/spinner.js
  yarn.lock
Labels: PR: New Feature

#4561 Edited Dockerfile of Docker(Nginx) deployment doc
  docs/guide/deployment.md
Labels: PR: Documentation

#4597 refactor: move jest configs into presets
  packages/@vue/cli-plugin-unit-jest/__tests__/jestGenerator.spec.js
  packages/@vue/cli-plugin-unit-jest/__tests__/jestPlugin.spec.js
  packages/@vue/cli-plugin-unit-jest/generator/index.js
  packages/@vue/cli-plugin-unit-jest/package.json
  packages/@vue/cli-plugin-unit-jest/preset/jest-preset.js
  packages/@vue/cli-plugin-unit-jest/preset/no-babel/esmoduleTransformer.js
  packages/@vue/cli-plugin-unit-jest/preset/no-babel/jest-preset.js
  packages/@vue/cli-plugin-unit-jest/preset/typescript-and-babel/jest-preset.js
  packages/@vue/cli-plugin-unit-jest/preset/typescript/jest-preset.js
Labels: PR: New Feature, PR: Underlying Tools

#4607 feat: use jsdom v15 in jest presets instead of the default v11
  packages/@vue/cli-plugin-unit-jest/package.json
  packages/@vue/cli-plugin-unit-jest/presets/default/jest-preset.js
Labels: PR: New Feature, PR: Underlying Tools

#4613 fix: correctly ignore html templates in copy-webpack-plugin
  packages/@vue/cli-service/__tests__/multiPage.spec.js
  packages/@vue/cli-service/lib/config/app.js
Labels: PR: Bug Fix

#4627 fix: fix nightwatch cli option (`--url`) handling
  packages/@vue/cli-plugin-e2e-nightwatch/__tests__/nightwatchPlugin.spec.js
  packages/@vue/cli-plugin-e2e-nightwatch/index.js
Labels: PR: Bug Fix

#4622 fix: fix nightwatch template's compatibility with eslint plugin
  packages/@vue/cli-plugin-e2e-nightwatch/__tests__/nightwatchPlugin.spec.js
  packages/@vue/cli-plugin-e2e-nightwatch/generator/index.js
  packages/@vue/cli-plugin-e2e-nightwatch/generator/template/tests/e2e/_eslintrc.js
  packages/@vue/cli-plugin-e2e-nightwatch/generator/template/tests/e2e/custom-assertions/elementCount.js
  packages/@vue/cli-plugin-e2e-nightwatch/generator/template/tests/e2e/custom-commands/customExecute.js
  packages/@vue/cli-plugin-e2e-nightwatch/generator/template/tests/e2e/custom-commands/openHomepage.js
  packages/@vue/cli-plugin-e2e-nightwatch/generator/template/tests/e2e/custom-commands/openHomepageClass.js
  packages/@vue/cli-plugin-e2e-nightwatch/generator/template/tests/e2e/globals.js
  packages/@vue/cli-plugin-e2e-nightwatch/generator/template/tests/e2e/page-objects/homepage.js
  packages/@vue/cli-plugin-e2e-nightwatch/generator/template/tests/e2e/specs/test-with-pageobjects.js
Labels: PR: Bug Fix

#4629 feat(babel): transform preset names in the plugin migrator
  .eslintignore
  packages/@vue/cli-plugin-babel/codemods/__testfixtures__/customConfig.input.js
  packages/@vue/cli-plugin-babel/codemods/__testfixtures__/customConfig.output.js
  packages/@vue/cli-plugin-babel/codemods/__testfixtures__/default.input.js
  packages/@vue/cli-plugin-babel/codemods/__testfixtures__/default.output.js
  packages/@vue/cli-plugin-babel/codemods/__testfixtures__/require.input.js
  packages/@vue/cli-plugin-babel/codemods/__testfixtures__/require.output.js
  packages/@vue/cli-plugin-babel/codemods/__testfixtures__/templateLiteral.input.js
  packages/@vue/cli-plugin-babel/codemods/__testfixtures__/templateLiteral.output.js
  packages/@vue/cli-plugin-babel/codemods/__tests__/usePluginPreset.spec.js
  packages/@vue/cli-plugin-babel/codemods/usePluginPreset.js
  packages/@vue/cli-plugin-babel/migrator/index.js
  packages/@vue/cli-plugin-babel/package.json
Labels: PR: New Feature

#4621 feat: support custom package manager
  packages/@vue/cli/lib/util/ProjectPackageManager.js
Labels: PR: New Feature

#4631 fix: fix sassOptions merging for scss syntax in sass-loader v8
  packages/@vue/cli-service/__tests__/css.spec.js
  packages/@vue/cli-service/lib/config/css.js
Labels: PR: Bug Fix

#4633 fix(babel-migrator): transform babel preset regardless of plugin version
  packages/@vue/cli-plugin-babel/migrator/index.js
Labels: PR: Bug Fix

#4634 fix(upgrade-all): avoid accidentally writing outdated package.json back
  packages/@vue/cli/lib/Upgrader.js
Labels: PR: Bug Fix
