Repository vuejs/vue-cli, pull requests merged in 2019-10, with the labels that each got.

#4637 fix: avoid accidentally overriding sass config with scss configs
  packages/@vue/cli-service/__tests__/css.spec.js
  packages/@vue/cli-service/lib/config/css.js
Labels: PR: Bug Fix

#4644 feat: add webdriver log files to gitignore
  packages/@vue/cli-service/generator/template/_gitignore
Labels: PR: New Feature

#4641 feat: make the minimizer config available in all modes
  packages/@vue/cli-service/lib/config/base.js
  packages/@vue/cli-service/lib/config/prod.js
Labels: PR: New Feature

#4654 fix: fix ie11 compatibility when css.extract set to true
  packages/@vue/cli-service/package.json
Labels: 3.x, PR: Bug Fix

#4662 [v3] Support sass-loader v8
  docs/guide/css.md
  docs/zh/guide/css.md
  packages/@vue/cli-service/__tests__/css.spec.js
  packages/@vue/cli-service/generator/index.js
  packages/@vue/cli-service/lib/config/css.js
  packages/@vue/cli-service/package.json
Labels: PR: New Feature

#4666 fix: fix redundant log messages from webpack-dev-server
  packages/@vue/cli-service/lib/commands/serve.js
Labels: PR: Bug Fix

#4664 feat(pwa): improve compatibility with v3 plugin usage
  packages/@vue/cli-plugin-pwa/index.js
Labels: PR: New Feature

#4663 feat(babel-preset): set target to node whenever NODE_ENV === 'test'
  packages/@vue/babel-preset-app/index.js
  packages/@vue/cli-plugin-unit-jest/index.js
  packages/@vue/cli-plugin-unit-mocha/index.js
Labels: PR: New Feature

#4673 refactor!: use DefinePlugin (again) instead of EnvironmentPlugin
  packages/@vue/cli-service/lib/commands/build/resolveWcConfig.js
  packages/@vue/cli-service/lib/config/app.js
  packages/@vue/cli-service/lib/config/base.js
  packages/@vue/cli-service/lib/util/resolveClientEnv.js
Labels: PR: Breaking Change, PR: Internal

#4676 chore!: upgrade terser-webpack-plugin to 2.x
  packages/@vue/cli-service/lib/config/terserOptions.js
  packages/@vue/cli-service/package.json
  yarn.lock
Labels: PR: Breaking Change, PR: Underlying Tools

#3926 chore: better upgrade messages
  packages/@vue/cli/lib/util/clearConsole.js
  packages/@vue/cli/package.json
Labels: PR: New Feature

#2319 missing documentation for building with vuex
  docs/guide/build-targets.md
Labels: PR: Documentation

#4552 docs: migration guide from v3 to v4
  docs/.vuepress/config.js
  docs/migrating-from-v3/README.md
Labels: PR: Documentation

#4681 chore!: add `@vue/cli` in `--version` output, to avoid confusion
  packages/@vue/cli/bin/vue.js
Labels: PR: Breaking Change

#4683 fix: Corrected typo in babel migrator
  packages/@vue/cli-plugin-babel/migrator/index.js
Labels: PR: Bug Fix

#4677 fix: add pnpm v4 support
  packages/@vue/cli-shared-utils/lib/env.js
  packages/@vue/cli/lib/util/ProjectPackageManager.js
Labels: PR: New Feature

#4693 fix: add a compatibility layer for router & vuex for CLI v3
  packages/@vue/cli-service/generator/index.js
Labels: PR: Bug Fix

#4697 fix: fix "lint on commit" projects generation error
  packages/@vue/cli-plugin-eslint/generator/index.js
  packages/@vue/cli-plugin-typescript/generator/index.js
  packages/@vue/cli-ui/package.json
Labels: PR: Bug Fix

#4696 fix: allow v3 cli to invoke vuex & router plugin from inside cli-service
  packages/@vue/cli-service/generator/index.js
  packages/@vue/cli-service/generator/router.js
  packages/@vue/cli-service/generator/vuex.js
  packages/@vue/cli-service/package.json
Labels: PR: Bug Fix

#4698 fix: fix `vue add router` command in v3 projects
  packages/@vue/cli-ui/ui-defaults/suggestions.js
  packages/@vue/cli/lib/add.js
Labels: PR: Bug Fix

#4702 Fix link to eslint PR
  docs/migrating-from-v3/README.md
Labels: PR: Documentation

#4706 Update README.md
  docs/migrating-from-v3/README.md
Labels: PR: Documentation

#4711 fix: fix a typo that caused router failed to install in older versions
  packages/@vue/cli-service/generator/router.js
Labels: PR: Bug Fix

#4712 fix(v3): do not install core plugins that have major version bumps
  packages/@vue/cli/lib/Creator.js
Labels: PR: Bug Fix

#4728 fix: fix eslint not found error in `vue serve` command
  packages/@vue/cli-plugin-eslint/index.js
Labels: PR: Bug Fix

#4720 fix: do not install core plugins that have major version bumps
  packages/@vue/cli/lib/Creator.js
Labels: PR: Bug Fix

#4734 chore: dependency maintenance
  package.json
  packages/@vue/babel-preset-app/package.json
  packages/@vue/cli-plugin-babel/generator.js
  packages/@vue/cli-plugin-babel/migrator/index.js
  packages/@vue/cli-plugin-babel/package.json
  packages/@vue/cli-plugin-e2e-cypress/package.json
  packages/@vue/cli-plugin-e2e-nightwatch/package.json
  packages/@vue/cli-plugin-eslint/generator/index.js
  packages/@vue/cli-plugin-router/generator/index.js
  packages/@vue/cli-plugin-typescript/__tests__/tsPlugin.helper.js
  packages/@vue/cli-plugin-typescript/generator/index.js
  packages/@vue/cli-plugin-typescript/package.json
  packages/@vue/cli-plugin-unit-jest/package.json
  packages/@vue/cli-plugin-unit-mocha/package.json
  packages/@vue/cli-service-global/__tests__/globalService.spec.js
  packages/@vue/cli-service-global/package.json
  packages/@vue/cli-service/__tests__/serve.spec.js
  packages/@vue/cli-service/generator/index.js
  packages/@vue/cli-service/package.json
  packages/@vue/cli-test-utils/package.json
  packages/@vue/cli-ui-addon-webpack/package.json
  packages/@vue/cli-ui-addon-widgets/package.json
  packages/@vue/cli-ui/package.json
  packages/@vue/cli/package.json
  yarn.lock
Labels: PR: Internal

#4733 Fix indentation of --inline-vue description
  docs/guide/cli-service.md
Labels: PR: Documentation

#4724 fix(ui): fix latest version check always displaying "0.1.0"
  packages/@vue/cli-ui/apollo-server/connectors/dependencies.js
Labels: PR: Bug Fix

#4739 fix(ui): "add router" button should not require prompt in terminal
  packages/@vue/cli-ui/ui-defaults/suggestions.js
Labels: PR: Bug Fix

#4740 fix(eslint): autofix code style after scaffolding on older versions of cli
  packages/@vue/cli-plugin-eslint/generator/index.js
Labels: PR: Bug Fix

#4741 fix: should tolerate cli version check error
  packages/@vue/cli/lib/util/clearConsole.js
  packages/@vue/cli/lib/util/getVersions.js
Labels: PR: Bug Fix
