Repository vuejs/vue-cli, pull requests merged in 2019-05, with the labels that each got.

#3909 chore: prefer .tsx? files over .jsx? file extensions
  packages/@vue/cli-plugin-typescript/index.js
Labels: PR: Breaking Change, semver: major

#3978 feat(babel-preset-app): Bump jsx dependency version
  packages/@vue/babel-preset-app/package.json
Labels: PR: Underlying Tools

#3943 chore: upgrade webpack-chain to v6
  packages/@vue/cli-service/package.json
Labels: PR: Underlying Tools

#3955 Feat rename project
  packages/@vue/cli-ui/apollo-server/connectors/projects.js
  packages/@vue/cli-ui/apollo-server/schema/project.js
  packages/@vue/cli-ui/locales/en.json
  packages/@vue/cli-ui/src/components/app/ProjectQuickDropdown.vue
  packages/@vue/cli-ui/src/components/project-manager/ProjectRename.vue
  packages/@vue/cli-ui/src/components/project-manager/ProjectSelectListItem.vue
  packages/@vue/cli-ui/src/components/view/ViewNav.vue
Labels: PR: New Feature, feat: ui

#3860 feat(cli): suggest matching commands if the user mistypes
  packages/@vue/cli/bin/vue.js
  packages/@vue/cli/package-lock.json
  packages/@vue/cli/package.json
Labels: PR: New Feature

#3975 chore!: change default value of `lintOnSave` option
  packages/@vue/cli-plugin-eslint/__tests__/eslintPlugin.spec.js
  packages/@vue/cli-service-global/index.js
  packages/@vue/cli-service/__tests__/Service.spec.js
  packages/@vue/cli-service/lib/options.js
  packages/@vue/cli-ui-addon-widgets/src/components/News.vue
  packages/@vue/cli/__tests__/Generator.spec.js
  packages/@vue/cli/__tests__/invoke.spec.js
Labels: PR: Breaking Change

#3992 fix(cli-ui): update dependencies and fix peer dependency warnings
  packages/@vue/cli-ui/package.json
Labels: PR: Bug Fix

#4003 refactor: replace recast with jscodeshift for `injectImportsAndOptions`
  packages/@vue/cli/__tests__/Generator.spec.js
  packages/@vue/cli/lib/util/injectImportsAndOptions.js
  packages/@vue/cli/package.json
Labels: PR: Internal

#4011 Enable HMR when extracting CSS in dev
  packages/@vue/cli-service/lib/config/css.js
Labels: PR: New Feature

#3927 fixed transformIgnorePatterns
  docs/config/README.md
  packages/@vue/cli-plugin-unit-jest/README.md
Labels: PR: Documentation, docs

#3929 Feat prompt editor
  docs/dev-guide/ui-api.md
  packages/@vue/cli-ui/src/components/prompt/Prompt.vue
  packages/@vue/cli-ui/src/components/prompt/PromptEditor.vue
Labels: PR: New Feature, feat: ui

#4025 fix: update the css-loader runtime path for css-loader v2
  packages/@vue/cli-service/lib/commands/build/resolveWcEntry.js
Labels: PR: Bug Fix

#4034 fix: fix dev mode compatibility with workers
  packages/@vue/cli-service/lib/config/dev.js
Labels: PR: Bug Fix

#4036 fix: add missing dependencies to @vue/cli-upgrade
  packages/@vue/cli-upgrade/package.json
Labels: PR: Bug Fix

#3939 feat(HtmlPwaPlugin): adds 'manifestCrossorigin' option
  packages/@vue/cli-plugin-pwa/lib/HtmlPwaPlugin.js
  packages/@vue/cli-plugin-pwa/ui.js
  packages/@vue/cli-ui/locales/en.json
Labels: PR: New Feature

#4046 docs: add description of babel plugin usage in TS plugin prompt
  packages/@vue/cli-plugin-typescript/prompts.js
  packages/@vue/cli/lib/promptModules/typescript.js
Labels: PR: Documentation

#3891 修改了一些翻译细节
  docs/zh/guide/plugins-and-presets.md
Labels: PR: Documentation

#3923 docs: fix dead link
  docs/dev-guide/plugin-dev.md
Labels: PR: Documentation

#3924 docs: add more explanation at prompts
  docs/dev-guide/plugin-dev.md
Labels: PR: Documentation

#4074 docs: redirect the links to v3 branch on github
  docs/.vuepress/config.js
Labels: PR: Documentation
