Repository vuejs/vue-cli, pull requests merged in 2019-08, with the labels that each got.

#4388 chore!: remove the already-deprecated `baseUrl` option
  packages/@vue/cli-service/__tests__/Service.spec.js
  packages/@vue/cli-service/lib/Service.js
  packages/@vue/cli-service/lib/options.js
  packages/@vue/cli-ui/locales/en.json
  packages/@vue/cli-ui/ui-defaults/config.js
Labels: PR: Breaking Change

#4385 style: add a "no-shadow" linter rule
  .eslintrc.js
  packages/@vue/cli-plugin-e2e-cypress/index.js
  packages/@vue/cli-plugin-e2e-nightwatch/index.js
  packages/@vue/cli-plugin-eslint/generator/index.js
  packages/@vue/cli-plugin-pwa/ui.js
  packages/@vue/cli-plugin-typescript/__tests__/tsPluginBabel.spec.js
  packages/@vue/cli-plugin-typescript/index.js
  packages/@vue/cli-plugin-typescript/lib/tslint.js
  packages/@vue/cli-service-global/index.js
  packages/@vue/cli-service-global/lib/globalConfigPlugin.js
  packages/@vue/cli-service/lib/Service.js
  packages/@vue/cli-service/lib/commands/build/formatStats.js
  packages/@vue/cli-service/lib/commands/build/resolveAppConfig.js
  packages/@vue/cli-service/lib/commands/help.js
  packages/@vue/cli-service/lib/commands/serve.js
  packages/@vue/cli-service/lib/config/app.js
  packages/@vue/cli-service/lib/webpack/analyzeBundle.js
  packages/@vue/cli-shared-utils/lib/object.js
  packages/@vue/cli-test-utils/serveWithPuppeteer.js
  packages/@vue/cli/bin/vue.js
  packages/@vue/cli/lib/GeneratorAPI.js
  packages/@vue/cli/lib/config.js
  packages/@vue/cli/lib/util/stringifyJS.js
Labels: PR: Internal

#4386 feat: allow configuring scss options separately from sass
  docs/config/README.md
  docs/guide/css.md
  docs/zh/config/README.md
  docs/zh/guide/css.md
  packages/@vue/cli-service/__tests__/css.spec.js
  packages/@vue/cli-service/lib/config/css.js
  packages/@vue/cli-service/lib/options.js
Labels: PR: New Feature

#4387 feat!: deprecate `css.modules` in favor of `css.requireModuleExtension`
  docs/config/README.md
  docs/guide/css.md
  docs/zh/config/README.md
  docs/zh/guide/css.md
  packages/@vue/cli-service/__tests__/css.spec.js
  packages/@vue/cli-service/lib/Service.js
  packages/@vue/cli-service/lib/config/css.js
  packages/@vue/cli-service/lib/options.js
Labels: PR: Breaking Change, PR: New Feature

#4396 docs(css): translate sass related content
  docs/zh/guide/css.md
Labels: PR: Documentation

#4395 docs: update Now deployment guide
  docs/guide/deployment.md
Labels: PR: Documentation

#4405 fix: `resolvePluginId` should correctly resolve `@vue/cli-service`
  packages/@vue/cli-shared-utils/lib/pluginResolution.js
Labels: PR: Bug Fix

#4404 feat: add `--next` flag to `vue upgrade` to check for beta versions
  packages/@vue/cli/bin/vue.js
  packages/@vue/cli/lib/Upgrader.js
  packages/@vue/cli/lib/upgrade.js
Labels: PR: New Feature

#4412 Adjusted deployment documentation for ZEIT Now
  docs/guide/deployment.md
Labels: PR: Documentation

#4420 Update parallel config description
  docs/config/README.md
Labels: PR: Documentation

#4253 feat: upgrade webpack
  package.json
  packages/@vue/cli-plugin-babel/package.json
  packages/@vue/cli-plugin-eslint/package.json
  packages/@vue/cli-plugin-pwa/package.json
  packages/@vue/cli-plugin-typescript/package.json
  packages/@vue/cli-service/__tests__/multiPage.spec.js
  packages/@vue/cli-service/package.json
Labels: PR: Underlying Tools, priority: next

#4416 chore: use a gitflow-like workflow for the project
  .github/COMMIT_CONVENTION.md
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: PR: Documentation

#4429 fix: merge custom `externals` config correctly, supports array
  packages/@vue/cli-service/lib/commands/build/resolveLibConfig.js
  packages/@vue/cli-service/lib/commands/build/resolveWcConfig.js
Labels: PR: Bug Fix

#4261 Add `--inline-vue` flag for `build` command to avoid externalization of Vue in lib & wc mode
  docs/guide/build-targets.md
  docs/guide/cli-service.md
  docs/ru/guide/build-targets.md
  docs/ru/guide/cli-service.md
  packages/@vue/cli-service/__tests__/buildLib.spec.js
  packages/@vue/cli-service/__tests__/buildWc.spec.js
  packages/@vue/cli-service/bin/vue-cli-service.js
  packages/@vue/cli-service/lib/commands/build/index.js
  packages/@vue/cli-service/lib/commands/build/resolveLibConfig.js
  packages/@vue/cli-service/lib/commands/build/resolveWcConfig.js
Labels: PR: New Feature

#4447 fix(eslint): eslint should override env
  packages/@vue/cli-plugin-unit-jest/generator/index.js
  packages/@vue/cli-plugin-unit-mocha/generator/index.js
Labels: PR: Bug Fix

#4448 feat: --skip-plugins
  docs/guide/cli-service.md
  packages/@vue/cli-service/__tests__/Service.spec.js
  packages/@vue/cli-service/lib/Service.js
  packages/@vue/cli-service/lib/commands/build/index.js
  packages/@vue/cli-service/lib/commands/inspect.js
  packages/@vue/cli-service/lib/commands/serve.js
Labels: PR: New Feature

#4468 feat: bump default less-loader version
  packages/@vue/cli-service/generator/index.js
Labels: PR: Bug Fix, PR: New Feature, PR: Underlying Tools

#4442 chore: add cwd option when calling globby
  packages/@vue/cli-plugin-eslint/lint.js
  packages/@vue/cli-ui/apollo-server/connectors/locales.js
  packages/@vue/cli-ui/apollo-server/resolvers.js
  packages/@vue/cli-ui/apollo-server/type-defs.js
Labels: PR: Bug Fix
