Repository vuejs/vue-cli, pull requests merged in 2019-07, with the labels that each got.

#4090 feat: implement a new `vue upgrade` command that supports code migration
  packages/@vue/cli-plugin-babel/migrator/index.js
  packages/@vue/cli-plugin-typescript/generator/index.js
  packages/@vue/cli-shared-utils/index.js
  packages/@vue/cli-shared-utils/lib/spinner.js
  packages/@vue/cli-ui/apollo-server/connectors/dependencies.js
  packages/@vue/cli-ui/apollo-server/connectors/plugins.js
  packages/@vue/cli-upgrade/bin/vue-cli-upgrade.js
  packages/@vue/cli-upgrade/get-upgradable-version.js
  packages/@vue/cli-upgrade/index.js
  packages/@vue/cli-upgrade/package.json
  packages/@vue/cli/__tests__/upgrade.spec.js
  packages/@vue/cli/bin/vue.js
  packages/@vue/cli/lib/Creator.js
  packages/@vue/cli/lib/GeneratorAPI.js
  packages/@vue/cli/lib/Migrator.js
  packages/@vue/cli/lib/MigratorAPI.js
  packages/@vue/cli/lib/add.js
  packages/@vue/cli/lib/invoke.js
  packages/@vue/cli/lib/upgrade.js
  packages/@vue/cli/lib/util/getInstalledVersion.js
  packages/@vue/cli/lib/util/getPackageJson.js
  packages/@vue/cli/lib/util/getPackageVersion.js
  packages/@vue/cli/lib/util/installDeps.js
  packages/@vue/cli/lib/util/linkBin.js
  packages/@vue/cli/lib/util/mergeDeps.js
  packages/@vue/cli/lib/util/packageManager.js
  packages/@vue/cli/lib/util/readFiles.js
  packages/@vue/cli/lib/util/tryGetNewerRange.js
  packages/@vue/cli/package.json
Labels: PR: Breaking Change, PR: New Feature

#4217 docs: add Render deployment guide
  docs/guide/deployment.md
Labels: PR: Documentation

#4233 fix: use module directory instead of main entry path for `eslintPath`
  packages/@vue/cli-plugin-eslint/index.js
Labels: PR: Bug Fix

#4103 deployment.md: Add instructions for Travis CI
  docs/guide/deployment.md
Labels: PR: Documentation

#4196 Make router a separate plugin
  docs/dev-guide/ui-api.md
  docs/guide/plugins-and-presets.md
  docs/ru/dev-guide/ui-api.md
  docs/ru/guide/plugins-and-presets.md
  docs/zh/guide/plugins-and-presets.md
  packages/@vue/cli-plugin-router/.npmignore
  packages/@vue/cli-plugin-router/README.md
  packages/@vue/cli-plugin-router/__tests__/routerGenerator.spec.js
  packages/@vue/cli-plugin-router/generator/index.js
  packages/@vue/cli-plugin-router/generator/template/src/App.vue
  packages/@vue/cli-plugin-router/generator/template/src/router/index.js
  packages/@vue/cli-plugin-router/generator/template/src/views/About.vue
  packages/@vue/cli-plugin-router/generator/template/src/views/Home.vue
  packages/@vue/cli-plugin-router/index.js
  packages/@vue/cli-plugin-router/package.json
  packages/@vue/cli-plugin-router/prompts.js
  packages/@vue/cli-plugin-typescript/__tests__/tsPluginE2e.spec.js
  packages/@vue/cli-plugin-typescript/generator/template/src/views/Home.vue
  packages/@vue/cli-service/__tests__/serve.spec.js
  packages/@vue/cli-service/generator/index.js
  packages/@vue/cli-service/generator/router/template/src/router.js
  packages/@vue/cli-service/generator/template/src/App.vue
  packages/@vue/cli-service/lib/PluginAPI.js
  packages/@vue/cli-ui/apollo-server/api/PluginApi.js
  packages/@vue/cli-ui/tests/e2e/specs/g2-plugins.js
  packages/@vue/cli-ui/ui-defaults/suggestions.js
  packages/@vue/cli/lib/Creator.js
  packages/@vue/cli/lib/Generator.js
  packages/@vue/cli/lib/add.js
  packages/@vue/cli/lib/options.js
  packages/@vue/cli/lib/promptModules/__tests__/router.spec.js
  packages/@vue/cli/lib/promptModules/router.js
  packages/@vue/cli/lib/util/features.js
Labels: PR: Breaking Change

#4241 Fix typos
  CHANGELOG.md
  docs/dev-guide/generator-api.md
  docs/dev-guide/plugin-api.md
  docs/dev-guide/plugin-dev.md
  docs/guide/mode-and-env.md
  docs/zh/guide/mode-and-env.md
  packages/@vue/babel-preset-app/index.js
  packages/@vue/cli-plugin-e2e-nightwatch/index.js
  packages/@vue/cli-plugin-eslint/lint.js
  packages/@vue/cli-service/__tests__/css.spec.js
  packages/@vue/cli-service/__tests__/modernMode.spec.js
  packages/@vue/cli-service/lib/commands/serve.js
  packages/@vue/cli-ui/apollo-server/api/PluginApi.js
  packages/@vue/cli-ui/apollo-server/connectors/plugins.js
  packages/@vue/cli-ui/src/vue-apollo.js
  packages/@vue/cli-ui/ui-defaults/widgets.js
  packages/@vue/cli/lib/upgrade.js
Labels: PR: Documentation

#4219 feat: allow omitting scope prefix for official plugins on `vue add`
  docs/core-plugins/babel.md
  docs/core-plugins/e2e-cypress.md
  docs/core-plugins/e2e-nightwatch.md
  docs/core-plugins/eslint.md
  docs/core-plugins/pwa.md
  docs/core-plugins/typescript.md
  docs/core-plugins/unit-jest.md
  docs/core-plugins/unit-mocha.md
  docs/guide/plugins-and-presets.md
  docs/ru/guide/plugins-and-presets.md
  docs/zh/guide/plugins-and-presets.md
  packages/@vue/cli-plugin-babel/README.md
  packages/@vue/cli-plugin-e2e-cypress/README.md
  packages/@vue/cli-plugin-e2e-nightwatch/README.md
  packages/@vue/cli-plugin-eslint/README.md
  packages/@vue/cli-plugin-pwa/README.md
  packages/@vue/cli-plugin-router/README.md
  packages/@vue/cli-plugin-typescript/README.md
  packages/@vue/cli-plugin-unit-jest/README.md
  packages/@vue/cli-plugin-unit-mocha/README.md
  packages/@vue/cli-plugin-vuex/README.md
  packages/@vue/cli-shared-utils/lib/pluginResolution.js
Labels: PR: New Feature

#4246 fix: fix eslint path resolution in `vue serve`
  packages/@vue/cli-plugin-eslint/index.js
Labels: PR: Bug Fix

#3320 docs(proxy): add warning when proxy set as string (fix #3308)
  docs/config/README.md
Labels: PR: Documentation

#4275 feat!: confirm before invoke/add/upgrade if project has uncommitted changes
  packages/@vue/cli/__tests__/invoke.spec.js
  packages/@vue/cli/lib/add.js
  packages/@vue/cli/lib/invoke.js
  packages/@vue/cli/lib/upgrade.js
  packages/@vue/cli/lib/util/confirmIfGitDirty.js
  scripts/testSetup.js
Labels: PR: Breaking Change, PR: New Feature

#4256 refactor: unify package manager related logic
  packages/@vue/cli-ui/apollo-server/connectors/dependencies.js
  packages/@vue/cli-ui/apollo-server/connectors/plugins.js
  packages/@vue/cli-ui/apollo-server/connectors/projects.js
  packages/@vue/cli/lib/Creator.js
  packages/@vue/cli/lib/add.js
  packages/@vue/cli/lib/invoke.js
  packages/@vue/cli/lib/upgrade.js
  packages/@vue/cli/lib/util/ProjectPackageManager.js
  packages/@vue/cli/lib/util/executeCommand.js
  packages/@vue/cli/lib/util/getInstalledVersion.js
  packages/@vue/cli/lib/util/getPackageVersion.js
  packages/@vue/cli/lib/util/getVersions.js
  packages/@vue/cli/lib/util/linkBin.js
  packages/@vue/cli/lib/util/packageManager.js
Labels: PR: Internal

#4232 Updated for Zeit Now V2
  docs/guide/deployment.md
Labels: PR: Documentation

#4230 fix: make webpack `use` values consistent
  packages/@vue/cli-service/lib/config/base.js
Labels: PR: Breaking Change

#4057 fix: indexPath should also affect non-production builds (#2327)
  packages/@vue/cli-service/lib/commands/build/index.js
  packages/@vue/cli-service/lib/config/app.js
Labels: PR: Bug Fix

#4171 Explain when .env files are loaded.
  docs/guide/mode-and-env.md
Labels: PR: Documentation

#4289 chore: deprecate tslint
  packages/@vue/cli/lib/promptModules/linter.js
Labels: PR: Underlying Tools

#4295 fix: fix latest version check when current version is a prerelease
  packages/@vue/cli/lib/options.js
  packages/@vue/cli/lib/util/getVersions.js
Labels: PR: Bug Fix

#4302 chore!: move dev configs into serve command
  packages/@vue/cli-service/lib/Service.js
  packages/@vue/cli-service/lib/commands/serve.js
  packages/@vue/cli-service/lib/config/dev.js
Labels: PR: Breaking Change, PR: Internal

#2337 More flexible hook system
  docs/dev-guide/generator-api.md
  docs/dev-guide/plugin-dev.md
  packages/@vue/cli-plugin-eslint/generator/index.js
  packages/@vue/cli/__tests__/Generator.spec.js
  packages/@vue/cli/lib/Creator.js
  packages/@vue/cli/lib/Generator.js
  packages/@vue/cli/lib/GeneratorAPI.js
  packages/@vue/cli/lib/add.js
  packages/@vue/cli/lib/invoke.js
Labels: PR: New Feature

#4323 chore!: ensure consistent directory structure for all modes
  packages/@vue/cli-service/lib/config/app.js
  packages/@vue/cli-service/lib/config/prod.js
Labels: PR: Breaking Change

#4320 Fixed: "Default value of the --filename parameter results in broken build if scoped package name is used #4311"
  packages/@vue/cli-service/__tests__/buildLib.spec.js
  packages/@vue/cli-service/lib/commands/build/resolveLibConfig.js
Labels: PR: Bug Fix

#4329 feat(eslint-generator): upgrade @vue/eslint-config-prettier to v5.0.0
  packages/@vue/cli-plugin-eslint/generator/index.js
Labels: PR: Bug Fix, PR: New Feature

#4330 fix: require parent template after `when` condition evaluated as truthy
  packages/@vue/cli/lib/GeneratorAPI.js
Labels: PR: Bug Fix

#4331 chore!: update versions of underlying webpack loaders
  packages/@vue/cli-service/package.json
Labels: PR: Breaking Change, PR: Underlying Tools

#4332 fix: when executing multiple actions, only check git status once
  packages/@vue/cli/lib/util/confirmIfGitDirty.js
Labels: PR: Bug Fix

#4336 fix: use `yarn --version` to detect yarn
  packages/@vue/cli-shared-utils/lib/env.js
Labels: PR: Bug Fix

#4257 Update mode-and-env.md
  docs/guide/mode-and-env.md
Labels: PR: Documentation

#4346 fix: fix typo in typescript generator, convertAllFiles -> convertJsToTs
  packages/@vue/cli-plugin-typescript/generator/convert.js
Labels: PR: Bug Fix

#4345 fix: fix css modules configuration in css-loader v3
  packages/@vue/cli-service/__tests__/css.spec.js
  packages/@vue/cli-service/lib/config/css.js
Labels: PR: Bug Fix

#4342 Add --port argument to 'vue serve' command
  docs/guide/prototyping.md
  packages/@vue/cli/bin/vue.js
Labels: PR: New Feature

#4367 chore(cli-service): word spelling in comments
  packages/@vue/cli-service/lib/commands/serve.js
  packages/@vue/cli/lib/GeneratorAPI.js
  packages/@vue/cli/lib/upgrade.js
Labels: PR: Internal

#4333 Update html-and-static-assets.md
  docs/ru/guide/html-and-static-assets.md
Labels: PR: Documentation

#4358 docs(ru): fix link in webpack.md
  docs/ru/guide/webpack.md
Labels: PR: Documentation

#4364 Replacing nightwatch CLI options URL with proper documentation
  docs/core-plugins/e2e-nightwatch.md
  packages/@vue/cli-plugin-e2e-nightwatch/README.md
  packages/@vue/cli-plugin-e2e-nightwatch/index.js
Labels: PR: Documentation

#4356 fix: `vue add` should be able to install prerelease versions for official plugins
  packages/@vue/cli/lib/add.js
Labels: PR: Bug Fix

#4365 chore: plugins should list @vue/cli-service in peerDependencies
  docs/dev-guide/generator-api.md
  docs/dev-guide/plugin-api.md
  packages/@vue/cli-plugin-babel/package.json
  packages/@vue/cli-plugin-e2e-cypress/package.json
  packages/@vue/cli-plugin-e2e-nightwatch/package.json
  packages/@vue/cli-plugin-eslint/package.json
  packages/@vue/cli-plugin-pwa/package.json
  packages/@vue/cli-plugin-router/package.json
  packages/@vue/cli-plugin-typescript/package.json
  packages/@vue/cli-plugin-unit-jest/package.json
  packages/@vue/cli-plugin-unit-mocha/package.json
  packages/@vue/cli-plugin-vuex/package.json
Labels: PR: Documentation, PR: Internal

#3897 feat(cli): Generator support async
  packages/@vue/cli/__tests__/Generator.spec.js
  packages/@vue/cli/__tests__/mock-preset-with-async-generator/generator/index.js
  packages/@vue/cli/__tests__/mock-preset-with-async-generator/generator/template/test.js
  packages/@vue/cli/__tests__/mock-preset-with-async-generator/preset.json
  packages/@vue/cli/__tests__/mock-preset-with-async-generator/prompts.js
  packages/@vue/cli/__tests__/preset.spec.js
  packages/@vue/cli/lib/Generator.js
Labels: PR: New Feature, feat: plugin API

#4363 fix: fix `css.loaderOptions.css.modules` default values
  docs/guide/css.md
  packages/@vue/cli-service/lib/Service.js
  packages/@vue/cli-service/lib/config/css.js
  packages/@vue/cli-service/lib/options.js
Labels: PR: Bug Fix

#2905 chore: ordered tslint rules
  packages/@vue/cli-plugin-typescript/generator/template/tslint.json
Labels: PR: Internal
