Repository vuejs/vue-cli, pull requests merged in 2019-03, with the labels that each got.

#3598 Update css.md
  docs/guide/css.md
Labels: PR: Documentation

#3656 docs: adjust plugin dev guide example to write modified contents, fixes #3655
  docs/dev-guide/plugin-dev.md
Labels: PR: Documentation

#3444 Add notes for multi-page apps on references to 'prefetch' plugin
  docs/guide/html-and-static-assets.md
Labels: PR: Documentation

#3686 Fix typo in README.md
  packages/@vue/cli-plugin-unit-jest/README.md
Labels: PR: Documentation

#3696 fix: explicitly set corejs version for @babel/preset-env
  package.json
  packages/@vue/babel-preset-app/index.js
  packages/@vue/babel-preset-app/package.json
  yarn.lock
Labels: PR: Bug Fix

#3710 fix: use absolute import path for injected core-js polyfills
  packages/@vue/babel-preset-app/__tests__/babel-preset.spec.js
  packages/@vue/babel-preset-app/package.json
  packages/@vue/babel-preset-app/polyfillsPlugin.js
Labels: PR: Bug Fix

#3663 feat: support pug as html template
  packages/@vue/cli-service/lib/config/base.js
Labels: PR: New Feature

#3647 fix: set the path of safari-no-module-fix.js correctly
  packages/@vue/cli-service/lib/commands/build/resolveAppConfig.js
  packages/@vue/cli-service/lib/webpack/ModernModePlugin.js
Labels: PR: Bug Fix

#3632 fix: properly load non-js config files in genCacheConfig
  packages/@vue/cli-service/lib/PluginAPI.js
Labels: PR: Bug Fix

#3716 fix: downgrade @babel/preset-env temporarily
  packages/@vue/babel-preset-app/index.js
  packages/@vue/babel-preset-app/package.json
  yarn.lock
Labels: PR: Bug Fix

#3702 Update browser-compatibility.md
  docs/ru/guide/browser-compatibility.md
Labels: PR: Documentation

#3730 fix: should not add polyfills from transform-runtime plugin
  packages/@vue/babel-preset-app/__tests__/babel-preset.spec.js
  packages/@vue/babel-preset-app/index.js
  packages/@vue/babel-preset-app/package.json
  packages/@vue/cli-plugin-babel/index.js
Labels: PR: Internal

#3732 fix: should not use absolute polyfill paths when `absoluteRuntime` is on
  packages/@vue/babel-preset-app/__tests__/babel-preset.spec.js
  packages/@vue/babel-preset-app/index.js
  packages/@vue/babel-preset-app/polyfillsPlugin.js
Labels: PR: Bug Fix

#3736 fix(generator): add core-js as direct dependency of generated projects
  packages/@vue/cli-plugin-babel/generator.js
Labels: PR: Bug Fix
