Repository vuejs/vue-cli, pull requests merged in 2019-06, with the labels that each got.

#4095 fix: fix resolve project local plugin's file path
  packages/@vue/cli-service/lib/Service.js
Labels: PR: Bug Fix

#4083 fix: display correct address when multiple network adapters present
  packages/@vue/cli-service/lib/util/prepareURLs.js
  packages/@vue/cli-service/package.json
Labels: PR: Bug Fix

#4120 Move core plugins docs to documentation website
  docs/.vuepress/config.js
  docs/core-plugins/README.md
  docs/core-plugins/babel.md
  docs/core-plugins/e2e-cypress.md
  docs/core-plugins/e2e-nightwatch.md
  docs/core-plugins/eslint.md
  docs/core-plugins/pwa.md
  docs/core-plugins/typescript.md
  docs/core-plugins/unit-jest.md
  docs/core-plugins/unit-mocha.md
  package.json
  scripts/genDocs.js
Labels: PR: Documentation

#4143 type error; sercet => secret
  docs/zh/guide/mode-and-env.md
Labels: PR: Documentation

#4150 chore: upgrade default-gateway to 5.0.2
  packages/@vue/cli-service/package.json
Labels: PR: Bug Fix

#4148 fix: fix config merging during `vue invoke` in Node.js v12
  packages/@vue/cli/lib/util/configTransforms.js
Labels: PR: Bug Fix

#4153 chore: move yorkie from cli-service to plugin-eslint & plugin-typescript
  packages/@vue/cli-plugin-eslint/package.json
  packages/@vue/cli-plugin-typescript/package.json
  packages/@vue/cli-service/package.json
Labels: PR: Internal

#4165 docs: Add Chinese translation for the part -- Installing plugin locally
  docs/zh/dev-guide/plugin-dev.md
Labels: PR: Documentation

#4168 feat: make `injectImports` & `injectRootOptions` work for `.vue` files
  packages/@vue/cli/__tests__/Generator.spec.js
  packages/@vue/cli/lib/Generator.js
  packages/@vue/cli/lib/util/codemods/injectImports.js
  packages/@vue/cli/lib/util/codemods/injectOptions.js
  packages/@vue/cli/lib/util/injectImportsAndOptions.js
  packages/@vue/cli/lib/util/runCodemod.js
  packages/@vue/cli/package.json
Labels: PR: New Feature

#3171 docs: Update issue template naming Issue Helper
  .github/ISSUE_TEMPLATE.md
Labels: PR: Documentation

#3857 docs: mention caveat about missing plugins when in legacy config
  docs/guide/browser-compatibility.md
Labels: PR: Documentation

#3777 Add heroku deployment guide
  docs/guide/deployment.md
Labels: PR: Documentation

#4000 feat: implement version-related APIs for `GeneratorAPI`
  docs/dev-guide/generator-api.md
  docs/dev-guide/plugin-api.md
  packages/@vue/cli/lib/GeneratorAPI.js
Labels: PR: New Feature

#4188 feat: add `transformScript` to GeneratorAPI
  packages/@vue/cli/__tests__/Generator.spec.js
  packages/@vue/cli/lib/GeneratorAPI.js
  packages/@vue/cli/package.json
Labels: PR: New Feature

#4205 Minor refactor to eliminate redundant code
  packages/@vue/cli/lib/util/installDeps.js
Labels: PR: Internal
