Repository vuejs/vue-cli, pull requests merged in 2019-12, with the labels that each got.

#4909 changed var-name `async` to `isAsync`
  packages/@vue/cli-service/lib/commands/build/resolveWcEntry.js
Labels: PR: Internal

#4924 fix: do not throw when babel config contains ignore/include/exclude
  packages/@vue/cli-plugin-babel/index.js
Labels: PR: Bug Fix

#4917 docs: [RU] Translation update
  docs/.vuepress/config.js
  docs/ru/README.md
  docs/ru/config/README.md
  docs/ru/core-plugins/README.md
  docs/ru/core-plugins/babel.md
  docs/ru/core-plugins/e2e-cypress.md
  docs/ru/core-plugins/e2e-nightwatch.md
  docs/ru/core-plugins/eslint.md
  docs/ru/core-plugins/pwa.md
  docs/ru/core-plugins/router.md
  docs/ru/core-plugins/typescript.md
  docs/ru/core-plugins/unit-jest.md
  docs/ru/core-plugins/unit-mocha.md
  docs/ru/core-plugins/vuex.md
  docs/ru/dev-guide/generator-api.md
  docs/ru/dev-guide/plugin-api.md
  docs/ru/dev-guide/plugin-dev.md
  docs/ru/dev-guide/ui-api.md
  docs/ru/dev-guide/ui-localization.md
  docs/ru/guide/browser-compatibility.md
  docs/ru/guide/build-targets.md
  docs/ru/guide/cli-service.md
  docs/ru/guide/creating-a-project.md
  docs/ru/guide/css.md
  docs/ru/guide/deployment.md
  docs/ru/guide/html-and-static-assets.md
  docs/ru/guide/installation.md
  docs/ru/guide/mode-and-env.md
  docs/ru/guide/plugins-and-presets.md
  docs/ru/guide/prototyping.md
  docs/ru/guide/troubleshooting.md
  docs/ru/guide/webpack.md
  docs/ru/migrating-from-v3/README.md
Labels: PR: Documentation

#4922 fix: should download to different directories for different presets
  packages/@vue/cli/lib/util/loadRemotePreset.js
Labels: PR: Bug Fix

#4904 refactor: use inline approach
  packages/@vue/cli/bin/vue.js
Labels: PR: Internal

#4973 docs: mention navigateFallback option for PWA App Shell caching
  docs/core-plugins/pwa.md
Labels: PR: Documentation

#4976 docs: his -> their
  docs/dev-guide/ui-api.md
Labels: PR: Documentation

#4754 Update debugging instructions
  packages/@vue/cli-plugin-unit-jest/README.md
Labels: PR: Documentation

#4974 fix: fix several bugs in the PWA plugin UI, make it usable again
  packages/@vue/cli-plugin-pwa/ui.js
Labels: PR: Bug Fix
