Repository vuejs/vue-cli, pull requests merged in 2020-08, with the labels that each got.

#5735 refactor(cli-service): webpack `devtool` option
  packages/@vue/cli-service/lib/commands/serve.js
Labels: PR: Internal

#5736 fix(e2e): shouldn't install webdrivers for unchecked browsers on creation
  packages/@vue/cli/lib/promptModules/__tests__/e2e.spec.js
  packages/@vue/cli/lib/promptModules/e2e.js
Labels: PR: Bug Fix

#5744 fix: ignore `.svn/**` when reading and writing files
  packages/@vue/cli/lib/util/readFiles.js
Labels: PR: Bug Fix

#5742 chore: dependency maintenance
  package.json
  packages/@vue/babel-preset-app/package.json
  packages/@vue/cli-plugin-babel/package.json
  packages/@vue/cli-plugin-e2e-nightwatch/package.json
  packages/@vue/cli-plugin-e2e-webdriverio/package.json
  packages/@vue/cli-plugin-typescript/__tests__/tsPlugin.helper.js
  packages/@vue/cli-plugin-typescript/__tests__/tsPluginVue3.spec.js
  packages/@vue/cli-plugin-unit-jest/package.json
  packages/@vue/cli-service/package.json
  packages/@vue/cli-test-utils/package.json
  yarn.lock
Labels: PR: Polish, PR: Underlying Tools

#5731 fix: fix skipLibCheck default value for `vue create`
  packages/@vue/cli-plugin-typescript/generator/index.js
  packages/@vue/cli-plugin-typescript/generator/template/tsconfig.json
Labels: PR: Bug Fix

#5753 refactor: output webdriverio logs to `tests/e2e/logs`
  packages/@vue/cli-plugin-e2e-webdriverio/generator/template/tests/e2e/logs/.gitkeep
  packages/@vue/cli-plugin-e2e-webdriverio/generator/template/wdio.shared.conf.js
  packages/@vue/cli-service/generator/template/_gitignore
Labels: PR: Polish

#5754 chore: use `stdout.columns` to determine the stats table width
  packages/@vue/cli-service/lib/commands/build/formatStats.js
Labels: PR: Polish

#5755 chore: default to non-class components for Vue 3 TS projects
  packages/@vue/cli/lib/promptModules/typescript.js
Labels: PR: Polish

#5728 docs: update deployment.md
  docs/ru/guide/deployment.md
Labels: PR: Documentation

#5768 fix: no longer need a shim for fork-ts-checker vue 3 support
  packages/@vue/cli-plugin-typescript/index.js
  packages/@vue/cli-plugin-typescript/vue-compiler-sfc-shim.js
Labels: PR: Bug Fix

#5694 [Fix] common misspelling errors
  CHANGELOG.md
  docs/config/README.md
  docs/dev-guide/ui-localization.md
  docs/guide/deployment.md
  packages/@vue/babel-preset-app/index.js
  packages/@vue/cli-plugin-e2e-nightwatch/__tests__/lib/globals-generated.js
  packages/@vue/cli-plugin-eslint/generator/index.js
  packages/@vue/cli-plugin-typescript/__tests__/tsPluginTSLint.spec.js
  packages/@vue/cli-service/lib/config/terserOptions.js
  packages/@vue/cli-service/lib/util/resolveLoaderError.js
  packages/@vue/cli/__tests__/invoke.spec.js
  packages/@vue/cli/lib/GeneratorAPI.js
  packages/@vue/cli/lib/util/confirmIfGitDirty.js
Labels: PR: Documentation, PR: Internal

#5771 fix: only replace App.vue when there's no router plugin
  packages/@vue/cli-plugin-typescript/generator/template/src/App.vue
Labels: PR: Bug Fix

#5769 fix: add missing mocha type if wdio is not installed along with any unit testing frameworks
  packages/@vue/cli-plugin-e2e-webdriverio/generator/index.js
  packages/@vue/cli-plugin-e2e-webdriverio/package.json
  packages/@vue/cli-plugin-typescript/generator/index.js
  packages/@vue/cli-plugin-typescript/generator/template/tsconfig.json
Labels: PR: Bug Fix

#5774 fix: load vue from `@vue/cli-service-global` on `vue serve`/`vue build`
  packages/@vue/cli-service/lib/config/base.js
Labels: PR: Bug Fix

#5778 fix: missing proxy argument
  packages/@vue/cli/bin/vue.js
Labels: PR: Bug Fix

#5693 fix: mayProxy.isPublicFileRequest judgment
  packages/@vue/cli-service/lib/util/prepareProxy.js
Labels: PR: Bug Fix

#5788 fix: ensure Dev Tool is enabled in Vue 3 runtime
  packages/@vue/cli-service/__tests__/serveVue3.spec.js
  packages/@vue/cli-service/lib/config/base.js
Labels: PR: Bug Fix

#5777 docs: add thread-loader warnings
  docs/config/README.md
  docs/core-plugins/babel.md
  docs/core-plugins/typescript.md
  packages/@vue/cli-plugin-babel/README.md
  packages/@vue/cli-plugin-typescript/README.md
Labels: PR: Documentation

#5798 fix: fix Vue 3 + TS + Router template
  packages/@vue/cli-plugin-typescript/generator/template-vue3/src/App.vue
Labels: PR: Bug Fix

#5804 fix: writeFileSync path was missing api.resolve
  docs/dev-guide/plugin-dev.md
Labels: PR: Documentation

#5801 fix: do not throw when api.render is called from an anonymous function
  packages/@vue/cli/__tests__/Generator.spec.js
  packages/@vue/cli/lib/GeneratorAPI.js
Labels: PR: Bug Fix

#5811 docs: update Node version requirement to address package manager issues
  docs/guide/installation.md
  docs/zh/guide/installation.md
Labels: PR: Documentation

#5808 fix: strip non-ansi characters from registry config
  packages/@vue/cli/lib/util/ProjectPackageManager.js
  packages/@vue/cli/package.json
Labels: PR: Bug Fix

#5815 Update deployment.md
  docs/guide/deployment.md
Labels: PR: Documentation

#5823 Handle GPG sign git config for initial commit
  packages/@vue/cli/lib/Creator.js
Labels: PR: Bug Fix

#5827 fix: fix support for Node.js v8 and deprecate it
  packages/@vue/cli/bin/vue.js
  packages/@vue/cli/lib/Creator.js
  packages/@vue/cli/lib/util/ProjectPackageManager.js
Labels: PR: Bug Fix

#5391 Remove ListFilter logic
  packages/@vue/cli-ui/src/components/dashboard/WidgetAddPane.vue
Labels: PR: Polish

#5807 Docs: Change zeit to vercel
  docs/guide/deployment.md
  docs/zh/guide/deployment.md
Labels: PR: Documentation

#5831 chore: rename jsx package scope from ant-design-vue to vue
  packages/@vue/babel-preset-app/README.md
  packages/@vue/babel-preset-app/index.js
  packages/@vue/babel-preset-app/package.json
Labels: PR: Underlying Tools

#5820 fix: allow turning off theme color tags
  packages/@vue/cli-plugin-pwa/lib/HtmlPwaPlugin.js
Labels: PR: Bug Fix
