Repository vuejs/vue-cli, pull requests merged in 2020-05, with the labels that each got.

#5408 docs: explain pwa head/manifest icons
  docs/core-plugins/pwa.md
Labels: PR: Documentation

#5443 fix: the translation of the scaffold
  docs/zh/guide/README.md
Labels: PR: Documentation

#5390 fix: set timeout of openChrome.applescript
  packages/@vue/cli-shared-utils/lib/openChrome.applescript
Labels: PR: Bug Fix

#5378 Update ui-api.md
  docs/zh/dev-guide/ui-api.md
Labels: PR: Documentation

#5416 removed ~1.4e7 superflous vertices
  packages/@vue/cli-plugin-pwa/generator/template/public/img/icons/safari-pinned-tab.svg
Labels: PR: Polish

#5349 docs: Update css.md
  docs/zh/guide/css.md
Labels: PR: Documentation

#5424 fix: normalize the `file` argument of `transformScript`, fix Windows compatibility
  packages/@vue/cli/lib/GeneratorAPI.js
Labels: PR: Bug Fix

#5376 feat(cli-service) add stdin flag to build
  packages/@vue/cli-service/lib/commands/build/index.js
Labels: PR: New Feature

#5395 Update ProjectPackageManager.js upgrade() method: manage multiple package names separated by spaces
  packages/@vue/cli/lib/util/ProjectPackageManager.js
Labels: PR: Bug Fix

#5455 fix(eslint): invalidate the cache when `.eslintignore` changes
  packages/@vue/cli-plugin-eslint/index.js
Labels: PR: Bug Fix

#4800 fix(serve): pass devServer sockPath properly to client
  packages/@vue/cli-service/lib/commands/serve.js
Labels: PR: Bug Fix

#5472 fix(creator): do not override the README.md generated by plugins
  packages/@vue/cli/__tests__/mock-preset-with-readme/generator.js
  packages/@vue/cli/__tests__/mock-preset-with-readme/preset.json
  packages/@vue/cli/__tests__/preset.spec.js
  packages/@vue/cli/lib/Creator.js
Labels: PR: Bug Fix

#5473 fixed --inspect-brk flag clobbering other values
  packages/@vue/cli-plugin-unit-mocha/index.js
Labels: PR: Bug Fix

#5493 fix(ui): the logs from creator should be displayed in the UI
  packages/@vue/cli/lib/Creator.js
Labels: PR: Bug Fix

#5496 chore: dependency maintenance
  package.json
  packages/@vue/babel-preset-app/package.json
  packages/@vue/cli-plugin-babel/package.json
  packages/@vue/cli-plugin-e2e-nightwatch/package.json
  packages/@vue/cli-plugin-eslint/eslintDeps.js
  packages/@vue/cli-plugin-typescript/package.json
  packages/@vue/cli-plugin-unit-jest/generator/index.js
  packages/@vue/cli-plugin-unit-jest/package.json
  packages/@vue/cli-plugin-unit-mocha/generator/index.js
  packages/@vue/cli-plugin-unit-mocha/package.json
  packages/@vue/cli-plugin-vuex/generator/index.js
  packages/@vue/cli-service/package.json
  packages/@vue/cli-ui-addon-webpack/package.json
  packages/@vue/cli-ui/package.json
  packages/@vue/cli/package.json
  yarn.lock
Labels: PR: Internal

#5497 fix: allow specifying plugin version when calling `vue add`
  packages/@vue/cli/lib/add.js
Labels: PR: Bug Fix

#5499 fix(unit-jest): fix .vue coverage report when babel plugin is not enabled
  packages/@vue/cli-plugin-unit-jest/__tests__/jestPlugin.spec.js
  packages/@vue/cli-plugin-unit-jest/presets/no-babel/jest-preset.js
Labels: PR: Bug Fix

#5498 feat(plugin-api): expose `inquirer` to prompts.js, allowing custom prompt types
  __mocks__/inquirer.js
  packages/@vue/cli/lib/Creator.js
  packages/@vue/cli/lib/invoke.js
Labels: PR: New Feature

#5500 fix: should throw errors if there is bad require() in vue.config.js
  packages/@vue/cli-service/__tests__/Service.spec.js
  packages/@vue/cli-service/__tests__/ServiceESM.spec.js
  packages/@vue/cli-service/__tests__/mockESM/package.json
  packages/@vue/cli-service/lib/Service.js
  packages/@vue/cli-shared-utils/lib/module.js
Labels: PR: Bug Fix

#5502 fix(cli): fix the creation log
  packages/@vue/cli/lib/Creator.js
Labels: PR: Bug Fix

#5513 refactor: improve the polyfill importing logic of modern mode
  packages/@vue/babel-preset-app/__tests__/babel-preset.spec.js
  packages/@vue/babel-preset-app/index.js
  packages/@vue/babel-preset-app/package.json
  packages/@vue/babel-preset-app/polyfillsPlugin.js
Labels: PR: Bug Fix, PR: Internal

#5530 Update README.md
  packages/@vue/cli-plugin-pwa/README.md
Labels: PR: Documentation

#5522 feat(babel-preset-app): pass full config to @babel/preset-env
  packages/@vue/babel-preset-app/__tests__/babel-preset.spec.js
  packages/@vue/babel-preset-app/index.js
Labels: PR: Internal
