Repository vuejs/vue-cli, pull requests merged in 2020-12, with the labels that each got.

#6092 chore: webpack-bundle-analyzer to ^4.1.0
  packages/@vue/cli-service/__tests__/build.spec.js
  packages/@vue/cli-service/package.json
Labels: PR: Underlying Tools

#6083 fix(cli-service): html template add html5 doctype declaration
  packages/@vue/cli-service/lib/commands/build/demo-lib-js.html
  packages/@vue/cli-service/lib/commands/build/demo-lib.html
  packages/@vue/cli-service/lib/commands/build/demo-wc.html
Labels: PR: Polish

#6090 chore: remove deprecated node-sass
  packages/@vue/cli-service/__tests__/generator.spec.js
  packages/@vue/cli-service/generator/index.js
  packages/@vue/cli/lib/options.js
  packages/@vue/cli/lib/promptModules/__tests__/cssPreprocessors.spec.js
  packages/@vue/cli/lib/promptModules/cssPreprocessors.js
  packages/@vue/cli/lib/util/ProjectPackageManager.js
  packages/@vue/cli/lib/util/inferRootOptions.js
  packages/@vue/cli/types/cli-test.ts
  packages/@vue/cli/types/index.d.ts
Labels: PR: Breaking Change

#6101 fix(cli-service): don't write entry-wc to node_modules
  .eslintignore
  packages/@vue/cli-service/lib/commands/build/.gitignore
  packages/@vue/cli-service/lib/commands/build/resolveWcConfig.js
  packages/@vue/cli-service/lib/commands/build/resolveWcEntry.js
  packages/@vue/cli-service/package.json
  yarn.lock
Labels: PR: Bug Fix

#6060 feat!: support and use webpack 5 as default
  .circleci/config.yml
  appveyor.yml
  docs/migrations/migrate-from-v4.md
  jest.config.js
  package.json
  packages/@vue/cli-plugin-babel/__tests__/babelRuntime.spec.js
  packages/@vue/cli-plugin-babel/package.json
  packages/@vue/cli-plugin-e2e-webdriverio/generator/template/tests/e2e/_eslintrc.js
  packages/@vue/cli-plugin-eslint/package.json
  packages/@vue/cli-plugin-pwa/__tests__/pwaPlugin.spec.js
  packages/@vue/cli-plugin-pwa/lib/HtmlPwaPlugin.js
  packages/@vue/cli-plugin-pwa/package.json
  packages/@vue/cli-plugin-typescript/__tests__/tsMochaPlugin.spec.js
  packages/@vue/cli-plugin-typescript/__tests__/tsPluginUnit.spec.js
  packages/@vue/cli-plugin-typescript/index.js
  packages/@vue/cli-plugin-typescript/package.json
  packages/@vue/cli-plugin-unit-mocha/__tests__/mochaPlugin.spec.js
  packages/@vue/cli-plugin-unit-mocha/generator/index.js
  packages/@vue/cli-service/__tests__/build.spec.js
  packages/@vue/cli-service/__tests__/buildWcAsync.spec.js
  packages/@vue/cli-service/__tests__/modernMode.spec.js
  packages/@vue/cli-service/__tests__/multiPage.spec.js
  packages/@vue/cli-service/lib/Service.js
  packages/@vue/cli-service/lib/commands/build/entry-wc.js
  packages/@vue/cli-service/lib/commands/build/resolveWcConfig.js
  packages/@vue/cli-service/lib/commands/build/resolveWcEntry.js
  packages/@vue/cli-service/lib/commands/serve.js
  packages/@vue/cli-service/lib/config/app.js
  packages/@vue/cli-service/lib/config/assets.js
  packages/@vue/cli-service/lib/config/base.js
  packages/@vue/cli-service/lib/config/css.js
  packages/@vue/cli-service/lib/config/prod.js
  packages/@vue/cli-service/lib/config/vue-loader-v15-resolve-compat/vue-loader.js
  packages/@vue/cli-service/lib/util/checkWebpack.js
  packages/@vue/cli-service/lib/util/getVueMajor.js
  packages/@vue/cli-service/lib/webpack/CorsPlugin.js
  packages/@vue/cli-service/lib/webpack/DashboardPlugin.js
  packages/@vue/cli-service/lib/webpack/ModernModePlugin.js
  packages/@vue/cli-service/lib/webpack/analyzeBundle.js
  packages/@vue/cli-service/package.json
  packages/@vue/cli-test-utils/createUpgradableProject.js
  packages/@vue/cli-ui/package.json
  scripts/test.js
  yarn.lock
Labels: PR: Breaking Change, PR: New Feature

#6094 feat: replace eslint-loader by eslint-webpack-plugin
  packages/@vue/cli-plugin-e2e-nightwatch/__tests__/nightwatchPlugin.spec.js
  packages/@vue/cli-plugin-eslint/__tests__/eslintPlugin.spec.js
  packages/@vue/cli-plugin-eslint/index.js
  packages/@vue/cli-plugin-eslint/package.json
  packages/@vue/cli-service-global/__tests__/globalService.spec.js
  packages/@vue/cli-service-global/lib/globalConfigPlugin.js
  yarn.lock
Labels: PR: Breaking Change, PR: New Feature

#6116 feat!: update jest to v26
  docs/migrations/migrate-from-v4.md
  package.json
  packages/@vue/cli-plugin-typescript/package.json
  packages/@vue/cli-plugin-unit-jest/package.json
  packages/@vue/cli-plugin-unit-jest/presets/default/jest-preset.js
  yarn.lock
Labels: PR: Breaking Change, PR: New Feature

#6115 feat!: make `vue serve/build` aliases to `npm run serve/build`
  docs/.vuepress/config.js
  docs/README.md
  docs/guide/README.md
  docs/guide/prototyping.md
  docs/migrations/migrate-from-v4.md
  packages/@vue/cli-service-global/.npmignore
  packages/@vue/cli-service-global/README.md
  packages/@vue/cli-service-global/__tests__/entry.vue
  packages/@vue/cli-service-global/__tests__/globalService.spec.js
  packages/@vue/cli-service-global/__tests__/globalServiceBuildLib.spec.js
  packages/@vue/cli-service-global/__tests__/globalServiceBuildWc.spec.js
  packages/@vue/cli-service-global/index.js
  packages/@vue/cli-service-global/lib/globalConfigPlugin.js
  packages/@vue/cli-service-global/lib/util.js
  packages/@vue/cli-service-global/package.json
  packages/@vue/cli-service-global/template/index.html
  packages/@vue/cli-service-global/template/main.js
  packages/@vue/cli/bin/vue.js
  packages/@vue/cli/lib/util/runNpmScript.js
  packages/@vue/cli/package.json
Labels: PR: Breaking Change, PR: New Feature

#6074 Fix Grammar Mistake in Docs
  docs/config/README.md
Labels: PR: Documentation

#6073 update Chinese doc: add entry default value
  docs/zh/guide/cli-service.md
Labels: PR: Documentation

#6108 feat!: upgrade postcss-loader, using postcss 8 by default
  docs/migrations/migrate-from-v4.md
  packages/@vue/cli-service/__tests__/css.spec.js
  packages/@vue/cli-service/__tests__/cssPreprocessors.spec.js
  packages/@vue/cli-service/lib/config/css.js
  packages/@vue/cli-service/package.json
  packages/@vue/cli-ui/vue.config.js
  yarn.lock
Labels: PR: Breaking Change, PR: New Feature

#6127 chore: update cmd-shim and move it to devDependencies
  packages/@vue/cli/package.json
Labels: PR: Internal

#6126 docs: add devServer.inline in config reference
  docs/config/README.md
Labels: PR: Documentation

#6128 docs: don't add `.loader()` when modifying vue-loader options
  docs/guide/webpack.md
  docs/ru/guide/webpack.md
  docs/zh/guide/webpack.md
Labels: PR: Documentation

#6120 feat: update cypress to v6
  docs/migrations/migrate-from-v4.md
  packages/@vue/cli-plugin-e2e-cypress/package.json
Labels: PR: New Feature

#6121 feat!: update mocha to v8
  docs/migrations/migrate-from-v4.md
  packages/@vue/cli-plugin-e2e-webdriverio/generator/index.js
  packages/@vue/cli-plugin-e2e-webdriverio/package.json
  packages/@vue/cli-plugin-typescript/package.json
  packages/@vue/cli-plugin-unit-mocha/generator/index.js
  packages/@vue/cli-plugin-unit-mocha/package.json
Labels: PR: Breaking Change, PR: New Feature

#6129 chore!: update typescript-related dependencies
  docs/migrations/migrate-from-v4.md
  package.json
  packages/@vue/cli-plugin-typescript/package.json
  packages/@vue/cli-plugin-unit-jest/generator/index.js
  packages/@vue/cli-ui/package.json
Labels: PR: Breaking Change, PR: New Feature

#6123 feat: update eslint-related packages
  docs/migrations/migrate-from-v4.md
  package.json
  packages/@vue/cli-plugin-eslint/eslintDeps.js
  packages/@vue/cli-ui-addon-webpack/package.json
  packages/@vue/cli-ui-addon-webpack/src/components/DonutModule.vue
  packages/@vue/cli-ui-addon-widgets/package.json
  packages/@vue/cli-ui/apollo-server/api/PluginApi.js
  packages/@vue/cli-ui/package.json
  yarn.lock
Labels: PR: New Feature

#6130 chore!: bump stylus-loader from v3 to v4
  packages/@vue/cli-service/generator/index.js
  packages/@vue/cli-service/lib/config/css.js
Labels: PR: Breaking Change, PR: New Feature

#6137 fix: fix usage of cmd-shim
  packages/@vue/cli/lib/util/linkBin.js
Labels: PR: Bug Fix

#6133 chore!: bump ejs to v3
  packages/@vue/cli/package.json
Labels: PR: Breaking Change, PR: Underlying Tools

#6136 feat: bump lint-staged to v10
  docs/guide/cli-service.md
  docs/ru/guide/cli-service.md
  docs/zh/guide/cli-service.md
  package.json
  packages/@vue/cli-plugin-eslint/__tests__/eslintGenerator.spec.js
  packages/@vue/cli-plugin-eslint/__tests__/eslintPlugin.spec.js
  packages/@vue/cli-plugin-eslint/generator/index.js
  packages/@vue/cli-service/migrator/index.js
  packages/@vue/cli-ui/package.json
Labels: PR: New Feature

#6132 chore!: prepare for v5 peer dependencies, drop v4 prereleases
  packages/@vue/cli-plugin-babel/package.json
  packages/@vue/cli-plugin-e2e-cypress/package.json
  packages/@vue/cli-plugin-e2e-nightwatch/package.json
  packages/@vue/cli-plugin-eslint/package.json
  packages/@vue/cli-plugin-pwa/package.json
  packages/@vue/cli-plugin-router/package.json
  packages/@vue/cli-plugin-typescript/package.json
  packages/@vue/cli-plugin-unit-jest/package.json
  packages/@vue/cli-plugin-unit-mocha/package.json
  packages/@vue/cli-plugin-vuex/package.json
Labels: PR: Breaking Change, PR: New Feature

#6140 refactor!: replace optimize-cssnano-plugin with css-minimizer-webpack-plugin
  packages/@vue/cli-service/__tests__/cssPreprocessors.spec.js
  packages/@vue/cli-service/lib/config/css.js
  packages/@vue/cli-service/lib/config/prod.js
  packages/@vue/cli-service/package.json
  packages/@vue/cli-ui/index.js
  yarn.lock
Labels: PR: Breaking Change, PR: Internal

#6145 fix: fix cypress mirror url for cypress version > 3
  packages/@vue/cli/lib/util/ProjectPackageManager.js
Labels: PR: Bug Fix

#6144 feat: add a @vue/cli-plugin-webpack-4 package for future use
  packages/@vue/cli-plugin-unit-mocha/generator/index.js
  packages/@vue/cli-plugin-unit-mocha/package.json
  packages/@vue/cli-plugin-webpack-4/README.md
  packages/@vue/cli-plugin-webpack-4/generator.js
  packages/@vue/cli-plugin-webpack-4/index.js
  packages/@vue/cli-plugin-webpack-4/package.json
  packages/@vue/cli-shared-utils/lib/pluginResolution.js
Labels: PR: New Feature

#6142 refactor: replace cache-loader with babel-loader's built-in cache
  docs/core-plugins/babel.md
  packages/@vue/cli-plugin-babel/README.md
  packages/@vue/cli-plugin-babel/index.js
  packages/@vue/cli-plugin-babel/package.json
  packages/@vue/cli-service/lib/PluginAPI.js
Labels: PR: Internal

#6050 mode-and-env doc need be updated
  docs/guide/mode-and-env.md
  docs/zh/guide/mode-and-env.md
Labels: PR: Documentation

#6152 chore: some trivial dependency version bumps
  package.json
  packages/@vue/cli-plugin-eslint/eslintDeps.js
  packages/@vue/cli-plugin-eslint/package.json
  packages/@vue/cli-plugin-typescript/package.json
  packages/@vue/cli-plugin-unit-jest/package.json
  packages/@vue/cli-service/package.json
  packages/@vue/cli-test-utils/package.json
  packages/@vue/cli-ui/apollo-server/connectors/configurations.js
  packages/@vue/cli-ui/package.json
  packages/@vue/cli/lib/util/stringifyJS.js
  packages/@vue/cli/package.json
  yarn.lock
Labels: PR: Internal

#6093 Easier Netlify setup
  docs/guide/deployment.md
Labels: PR: Documentation

#5993 refactor(generator): minor refactor afterInvoke/afterAnyInvoke
  packages/@vue/cli/__tests__/Generator.spec.js
  packages/@vue/cli/lib/Generator.js
Labels: PR: Polish

#6011 fix(generator): avoid doing redundant write operations
  packages/@vue/cli/__tests__/Generator.spec.js
  packages/@vue/cli/lib/Generator.js
  packages/@vue/cli/lib/util/writeFileTree.js
Labels: PR: Bug Fix

#5537 feat(cli): make globby includes dot files
  packages/@vue/cli/lib/GeneratorAPI.js
Labels: PR: New Feature

#5927 Update skip plugins section of cli-service
  docs/guide/cli-service.md
Labels: PR: Documentation

#6170 fix: add missing jest-transform-stub media types (#6169)
  packages/@vue/cli-plugin-unit-jest/presets/default/jest-preset.js
Labels: PR: Bug Fix

#6176 Fixed some typos on deployment.md
  docs/guide/deployment.md
Labels: PR: Documentation
