Repository vuejs/vue-cli, pull requests merged in 2020-10, with the labels that each got.

#5835 Update Vercel deployment instructions
  docs/guide/deployment.md
Labels: PR: Documentation

#4850 feat(lint): add output file option (close #4849)
  packages/@vue/cli-plugin-eslint/README.md
  packages/@vue/cli-plugin-eslint/__tests__/eslintPlugin.spec.js
  packages/@vue/cli-plugin-eslint/index.js
  packages/@vue/cli-plugin-eslint/lint.js
Labels: PR: New Feature

#5941 feat!: bump fork-ts-checker-webpack-plugin version to v5
  docs/migrations/migrate-from-v4.md
  packages/@vue/cli-plugin-typescript/index.js
  packages/@vue/cli-plugin-typescript/package.json
Labels: PR: Breaking Change

#5961 fix: npm 7 compat by turning on `legacy-peer-deps` flag
  packages/@vue/cli/lib/util/ProjectPackageManager.js
Labels: PR: Bug Fix

#5962 fix: narrow the eslint peer dep version range, avoiding npm 7 error
  packages/@vue/cli-plugin-eslint/package.json
Labels: PR: Bug Fix

#5951 chore!: some trivial dependency major version updates
  docs/migrations/migrate-from-v4.md
  packages/@vue/cli-plugin-babel/package.json
  packages/@vue/cli-plugin-typescript/package.json
  packages/@vue/cli-service/lib/config/app.js
  packages/@vue/cli-service/lib/config/base.js
  packages/@vue/cli-service/package.json
  yarn.lock
Labels: PR: Breaking Change

#5975 fix: update vue-shims for Vue v3.0.1
  packages/@vue/cli-plugin-typescript/generator/template-vue3/src/shims-vue.d.ts
Labels: PR: Bug Fix
