Repository vuejs/vue-cli, pull requests merged in 2020-02, with the labels that each got.

#5108 fix(e2e-cypress): make --headless work with --browser chrome
  packages/@vue/cli-plugin-e2e-cypress/index.js
  packages/@vue/cli-plugin-e2e-cypress/package.json
Labels: PR: Bug Fix

#5126 fix(docs): new travis CLI interface
  docs/guide/deployment.md
Labels: PR: Documentation

#5128 feat: upgrade to typescript@~3.7.5
  package.json
  packages/@vue/cli-plugin-typescript/generator/index.js
  packages/@vue/cli-plugin-typescript/package.json
  packages/@vue/cli-ui/package.json
  yarn.lock
Labels: PR: New Feature

#4985 fix(CORS): only allow connections from the designated host
  packages/@vue/cli-ui/graphql-server.js
  packages/@vue/cli-ui/package.json
  packages/@vue/cli-ui/server.js
  packages/@vue/cli/lib/ui.js
  yarn.lock
Labels: PR: Bug Fix

#5134 feat: lock minor versions when creating projects / adding plugins
  packages/@vue/cli-ui/apollo-server/connectors/dependencies.js
  packages/@vue/cli/lib/Creator.js
  packages/@vue/cli/lib/Upgrader.js
  packages/@vue/cli/lib/add.js
  packages/@vue/cli/lib/util/ProjectPackageManager.js
  packages/@vue/cli/lib/util/getVersions.js
Labels: PR: New Feature

#5142 fix(cors): fixup #4985, allow same-origin ws requests of any domain
  packages/@vue/cli/lib/ui.js
Labels: PR: Bug Fix

#5147 feat: create projects with @vue/test-utils beta 31
  packages/@vue/cli-plugin-unit-jest/generator/index.js
  packages/@vue/cli-plugin-unit-jest/package.json
  packages/@vue/cli-plugin-unit-mocha/generator/index.js
  packages/@vue/cli-plugin-unit-mocha/package.json
  yarn.lock
Labels: PR: New Feature

#5149 feat(GeneratorAPI): allow passing options to `api.extendPackage`
  packages/@vue/cli-plugin-babel/migrator/index.js
  packages/@vue/cli-plugin-eslint/migrator/index.js
  packages/@vue/cli-plugin-typescript/migrator/index.js
  packages/@vue/cli/__tests__/Generator.spec.js
  packages/@vue/cli/lib/GeneratorAPI.js
  packages/@vue/cli/lib/util/mergeDeps.js
Labels: PR: New Feature

#5150 fix: should infer package manager from config if there's no lockfile in the project
  packages/@vue/cli-shared-utils/lib/env.js
  packages/@vue/cli/lib/util/ProjectPackageManager.js
Labels: PR: Bug Fix

#5117 :pencil: docs: Set base property of VueRouter when deploying to gh-pages
  docs/guide/deployment.md
Labels: PR: Documentation

#5157 docs(zh): fix typos
  docs/zh/config/README.md
Labels: PR: Documentation

#5166 chore: switch over to leven for command suggestion
  packages/@vue/cli/bin/vue.js
  packages/@vue/cli/package.json
  yarn.lock
Labels: PR: Internal

#5176 Added basic upgrading instructions
  docs/guide/installation.md
Labels: PR: Documentation

#5141 docs(zh): Update now 404 url
  docs/zh/guide/deployment.md
Labels: PR: Documentation

#5209 docs(zh): update example format
  docs/zh/guide/mode-and-env.md
Labels: PR: Documentation

#5184 Remove unnecessary hyphen
  docs/ru/guide/cli-service.md
Labels: PR: Documentation

#5224 Update mode-and-env.md
  docs/zh/guide/mode-and-env.md
Labels: PR: Documentation

#5196 fix(cli-service-global): fix no-debugger rule config
  packages/@vue/cli-service-global/lib/globalConfigPlugin.js
Labels: PR: Bug Fix

#5202 fix(GeneratorAPI): remove warning when using extendPackage with prune
  packages/@vue/cli/__tests__/Generator.spec.js
  packages/@vue/cli/lib/util/mergeDeps.js
Labels: PR: Bug Fix

#5163 fix "Vue packages version mismatch" error caused by other global packages
  packages/@vue/cli/package.json
Labels: PR: Bug Fix

#4805 types(router): added router array type for Array RouteConfig
  packages/@vue/cli-plugin-router/generator/index.js
  packages/@vue/cli-plugin-router/generator/template/src/router/index.js
Labels: PR: New Feature

#5226 docs: fix readme of @vue/cli-plugin-eslint
  packages/@vue/cli-plugin-eslint/README.md
Labels: PR: Documentation
