Repository vuejs/vue-cli, pull requests merged in 2020-11, with the labels that each got.

#6036 docs(zh): correction of some format problems
  docs/zh/dev-guide/plugin-dev.md
Labels: PR: Documentation

#6005 docs: [RU] Translation update
  docs/ru/config/README.md
  docs/ru/core-plugins/babel.md
  docs/ru/core-plugins/e2e-webdriverio.md
  docs/ru/core-plugins/typescript.md
  docs/ru/dev-guide/plugin-dev.md
  docs/ru/guide/deployment.md
  docs/ru/guide/installation.md
  docs/ru/guide/mode-and-env.md
  docs/ru/guide/plugins-and-presets.md
  docs/ru/guide/webpack.md
Labels: PR: Documentation

#6009 refactor!: replace request with node-fetch
  package.json
  packages/@vue/cli-service/__tests__/proxy.spec.js
  packages/@vue/cli-shared-utils/lib/request.js
  packages/@vue/cli-shared-utils/package.json
  packages/@vue/cli/lib/util/ProjectPackageManager.js
  scripts/checkLinks.js
  scripts/syncDeps.js
  yarn.lock
Labels: PR: Breaking Change, PR: Internal

#5921 fix(cli): only process template file contents, bump yaml-front-matter…
  packages/@vue/cli/package.json
Labels: PR: Bug Fix

#6000 fix: prevent snoretoast shortcut, set notif title (#2720)
  packages/@vue/cli-ui/apollo-server/util/notification.js
Labels: PR: Bug Fix, PR: Polish

#6053 fix(cli-plugin-typescript): remove getPrompts function in prompts.js
  packages/@vue/cli-plugin-typescript/prompts.js
Labels: PR: Internal

#6051 chore!: drop support of NPM 5
  docs/migrations/migrate-from-v4.md
  packages/@vue/cli-service/package.json
  packages/@vue/cli/lib/util/ProjectPackageManager.js
Labels: PR: Breaking Change

#6052 chore!: drop support of end-of-life node releases (8, 11, 13)
  packages/@vue/cli-service/package.json
  packages/@vue/cli-ui/package.json
  packages/@vue/cli/lib/Creator.js
  packages/@vue/cli/package.json
Labels: PR: Breaking Change

#6062 fix(cypress): allow users to update cypress
  packages/@vue/cli-plugin-e2e-cypress/index.js
Labels: PR: New Feature

#5973 chore!: bump joi to v17
  docs/migrations/migrate-from-v4.md
  packages/@vue/cli-service/lib/options.js
  packages/@vue/cli-shared-utils/lib/validate.js
  packages/@vue/cli-shared-utils/package.json
  packages/@vue/cli-ui/apollo-server/api/task.js
  packages/@vue/cli/lib/options.js
  yarn.lock
Labels: PR: Breaking Change, PR: Internal

#6059 feat(eslint): support eslint7 and @babel/eslint-parser
  package.json
  packages/@vue/cli-plugin-eslint/__tests__/eslintGenerator.spec.js
  packages/@vue/cli-plugin-eslint/__tests__/eslintMigrator.spec.js
  packages/@vue/cli-plugin-eslint/eslintDeps.js
  packages/@vue/cli-plugin-eslint/eslintOptions.js
  packages/@vue/cli-plugin-eslint/migrator/index.js
  packages/@vue/cli-plugin-eslint/package.json
  packages/@vue/cli-test-utils/createUpgradableProject.js
  packages/@vue/cli-ui/.eslintrc.js
  packages/@vue/cli/__tests__/invoke.spec.js
  yarn.lock
Labels: PR: New Feature

#6078 refactor: sub-package eslint maintance
  .eslintrc.js
  packages/@vue/cli-service-global/__tests__/entry.vue
  packages/@vue/cli-service-global/__tests__/globalService.spec.js
  packages/@vue/cli-service-global/lib/globalConfigPlugin.js
  packages/@vue/cli-service-global/package.json
  packages/@vue/cli-ui-addon-webpack/.eslintrc.js
  packages/@vue/cli-ui-addon-webpack/package.json
  packages/@vue/cli-ui-addon-widgets/.eslintrc.js
  packages/@vue/cli-ui-addon-widgets/package.json
  packages/@vue/cli-ui/.eslintrc.js
  packages/@vue/cli-ui/package.json
  yarn.lock
Labels: PR: Internal

#6085 Update Render deployment guide
  docs/guide/deployment.md
Labels: PR: Documentation

#6020 fix(generator): upgrade to prettier v2
  packages/@vue/cli-plugin-eslint/eslintDeps.js
Labels: PR: Bug Fix

#6097 fix(mocha): disable SSR optimization for Vue 3 testing
  packages/@vue/cli-plugin-unit-mocha/index.js
  packages/@vue/cli-service/package.json
Labels: PR: Bug Fix
