Repository vuejs/vue-cli, pull requests merged in 2020-03, with the labels that each got.

#5236 fix(babel-preset-app): avoid corejs warning when useBuiltIns is false
  packages/@vue/babel-preset-app/index.js
Labels: PR: Bug Fix

#5231 Update plugin-dev.md
  docs/dev-guide/plugin-dev.md
Labels: PR: Documentation

#5243 docs: add warning on client side environment variables
  docs/guide/mode-and-env.md
Labels: PR: Documentation

#5238 Improve package.json not found error 
  packages/@vue/cli/lib/util/getPkg.js
Labels: PR: Internal

#5228 test: test case for command suggestion logic
  packages/@vue/cli/__tests__/args.spec.js
Labels: PR: Internal

#5264 fix false positive of `hasProjectNpm`
  packages/@vue/cli-shared-utils/lib/env.js
Labels: PR: Bug Fix

#5233 feat: add "not dead" to the default browserslist query
  packages/@vue/cli-service/generator/index.js
  packages/@vue/cli-ui-addon-webpack/package.json
  packages/@vue/cli-ui-addon-widgets/.browserslistrc
  packages/@vue/cli-ui/package.json
Labels: PR: New Feature

#5241 feat: ease the default `no-console` severity to `warn`
  packages/@vue/cli-plugin-eslint/eslintOptions.js
  packages/@vue/cli-service-global/lib/globalConfigPlugin.js
  packages/@vue/cli-ui-addon-widgets/.eslintrc.js
Labels: PR: New Feature

#5242 fix: fix severity config in ui
  packages/@vue/cli-plugin-eslint/__tests__/ui.spec.js
  packages/@vue/cli-plugin-eslint/ui/configDescriptor.js
Labels: PR: Bug Fix

#5273 chore(eslint): bump minimum required eslint-loader version to support ESLint 6
  packages/@vue/cli-plugin-eslint/package.json
  yarn.lock
Labels: PR: Underlying Tools

#5170 feat: use @vue/compiler-sfc as a compiler for TS if available
  packages/@vue/cli-plugin-typescript/index.js
  packages/@vue/cli-plugin-typescript/package.json
  packages/@vue/cli-plugin-typescript/vue-compiler-sfc-shim.js
Labels: PR: New Feature

#5087 feat(pwa): Check for null or undefined in iconPaths
  packages/@vue/cli-plugin-pwa/lib/HtmlPwaPlugin.js
Labels: PR: Bug Fix

#5282 docs: update polyfill names according to core-js 3
  docs/guide/browser-compatibility.md
  docs/ru/guide/browser-compatibility.md
  docs/zh/guide/browser-compatibility.md
  packages/@vue/babel-preset-app/README.md
Labels: PR: Documentation

#5212 feat(vue-cli): Choosing to save as a preset tells you where it is saved
  packages/@vue/cli/lib/Creator.js
  packages/@vue/cli/lib/options.js
Labels: PR: New Feature

#3886 Fix wc entry to allow multiple file patterns
  packages/@vue/cli-service/lib/commands/build/resolveWcConfig.js
Labels: PR: New Feature

#5300 Update cli-service.md
  docs/zh/guide/cli-service.md
Labels: PR: Documentation

#5247 fix(target-lib): fix dynamic public path in a dynamic chunk in Firefox
  packages/@vue/cli-service/lib/commands/build/setPublicPath.js
  packages/@vue/cli-service/package.json
  yarn.lock
Labels: PR: Bug Fix

#5305 refactor: simplify config loading by skipping `fs.existsSync` check
  packages/@vue/cli-service/__tests__/Service.spec.js
  packages/@vue/cli-service/lib/Service.js
Labels: PR: Internal

#5320 fix: spawn scripts with node, fix modern mode with Yarn 2 (Berry)
  packages/@vue/cli-service/lib/commands/build/index.js
Labels: PR: Bug Fix

#5319 chore(cli-service-global): remove direct dependency on `@vue/babel-preset-app`
  packages/@vue/cli-service-global/lib/globalConfigPlugin.js
  packages/@vue/cli-service-global/package.json
Labels: PR: Internal

#5290 fix(cli-ui): build task defaults should respect outputDir option from config file (fix #2639)
  packages/@vue/cli-ui/ui-defaults/tasks.js
Labels: PR: Bug Fix

#5293 support vue.config.cjs
  packages/@vue/cli-service/__tests__/Service.spec.js
  packages/@vue/cli-service/__tests__/ServiceESM.spec.js
  packages/@vue/cli-service/__tests__/mockESM/package.json
  packages/@vue/cli-service/lib/Service.js
  yarn.lock
Labels: PR: New Feature

#5315 fix: avoid process hanging when trying to get Chrome version
  packages/@vue/cli-shared-utils/index.js
  packages/@vue/cli-shared-utils/lib/env.js
Labels: PR: Bug Fix

#5312 Make Heroku resource link accessible
  docs/guide/deployment.md
Labels: PR: Documentation

#5322 feat: enable `bugfixes` option for babel by default
  packages/@vue/babel-preset-app/index.js
  packages/@vue/babel-preset-app/package.json
Labels: PR: New Feature
