Repository vuejs/vue-cli, pull requests merged in 2020-04, with the labels that each got.

#5294 feat(service): Allow mocha unit tests debugger to be bound to a specified IP and port
  packages/@vue/cli-plugin-unit-mocha/index.js
Labels: PR: New Feature

#5360 fix: run migrator in a separator process, fix require cache issues during upgrade
  packages/@vue/cli/lib/Upgrader.js
Labels: PR: Bug Fix

#5363 fix(eslint-migrator): fix local eslint major version detection
  packages/@vue/cli-plugin-eslint/migrator/index.js
Labels: PR: Bug Fix

#5387 [cli-plugin-e2e-nightwatch] fixing globals.js import
  packages/@vue/cli-plugin-e2e-nightwatch/nightwatch.config.js
Labels: PR: Bug Fix

#5384 docs: [RU] Translation update
  docs/ru/core-plugins/eslint.md
  docs/ru/guide/deployment.md
Labels: PR: Documentation
