Repository vuejs/vue-cli, pull requests merged in 2020-06, with the labels that each got.

#5540 fix: add `--no-verify` to initial git commit
  packages/@vue/cli/lib/Creator.js
Labels: PR: Bug Fix

#5542 fix(cli-service): process the webpack failed hook in the serve command
  packages/@vue/cli-service/lib/commands/serve.js
Labels: PR: Bug Fix

#5539 fix: correctly shim @vue/compiler-sfc for fork-ts-checker-plugin
  packages/@vue/cli-plugin-typescript/vue-compiler-sfc-shim.js
Labels: PR: Bug Fix

#5545 fix: @vue/cli-plugin-eslint upgrade prompt eslint need to upgrade fro…
  packages/@vue/cli-plugin-eslint/migrator/index.js
Labels: PR: Bug Fix

#5544 fix(cli-service): fix polyfill injection when overriding `entry` with the CLI option
  packages/@vue/cli-service/lib/commands/build/resolveAppConfig.js
Labels: PR: Bug Fix

#5571 docs: add documentation for `manifestCrossorigin`
  packages/@vue/cli-plugin-pwa/README.md
  packages/@vue/cli-ui/locales/en.json
Labels: PR: Documentation

#5576 fix: should return the parse result in the compiler-sfc-shim
  packages/@vue/cli-plugin-typescript/vue-compiler-sfc-shim.js
Labels: PR: Bug Fix

#5572 refactor: replace request-promise-native with util.promisify
  packages/@vue/cli-shared-utils/lib/request.js
  packages/@vue/cli-shared-utils/package.json
Labels: PR: Internal

#5579 docs: update cli eslint plugin configuration
  docs/core-plugins/eslint.md
  packages/@vue/cli-plugin-eslint/README.md
Labels: PR: Documentation

#5528 fix(nightwatch): should not install corresponding webdriver if the browser is unselected
  packages/@vue/cli-plugin-e2e-nightwatch/generator/index.js
Labels: PR: Bug Fix

#5586 fix: support auth token when retrieving package metadata
  packages/@vue/cli/lib/util/ProjectPackageManager.js
  packages/@vue/cli/package.json
Labels: PR: Bug Fix

#5580 Fix: stop ignoring --config-file cypress option
  packages/@vue/cli-plugin-e2e-cypress/index.js
Labels: PR: Bug Fix

#5345 docs: translate plugin-dev
  docs/zh/dev-guide/plugin-dev.md
Labels: PR: Documentation

#5598 fix: fix an edge case that VUE_CLI_SERVICE_CONFIG_PATH might be ignored
  packages/@vue/cli-service/lib/Service.js
Labels: PR: Bug Fix

#5592 fix polyfill injection when building app on multiple threads
  packages/@vue/cli-service/__tests__/Service.spec.js
  packages/@vue/cli-service/lib/Service.js
  packages/@vue/cli-service/lib/commands/build/resolveAppConfig.js
Labels: PR: Bug Fix

#5603 docs: @babel-preset/env -> @babel/preset-env
  docs/guide/browser-compatibility.md
  docs/ru/guide/browser-compatibility.md
  docs/zh/guide/browser-compatibility.md
Labels: PR: Documentation

#5604 chore: improve error message when get metadata failed
  packages/@vue/cli-shared-utils/lib/logger.js
  packages/@vue/cli-shared-utils/lib/spinner.js
  packages/@vue/cli/lib/util/ProjectPackageManager.js
Labels: PR: Polish

#5609 fix: fix support for some legacy registry servers
  packages/@vue/cli/lib/util/ProjectPackageManager.js
Labels: PR: Bug Fix

#5614 fix jscodeshift peer dependency error
  packages/@vue/cli/package.json
  yarn.lock
Labels: PR: Bug Fix

#5556 feat: support node nightly builds
  packages/@vue/cli-service/bin/vue-cli-service.js
  packages/@vue/cli/bin/vue.js
Labels: PR: New Feature

#5543 fix: better error message for non-existent polyfill names
  packages/@vue/babel-preset-app/index.js
Labels: PR: Bug Fix

#5570 feat: detect and compile Vue 3 projects
  packages/@vue/cli-plugin-typescript/package.json
  packages/@vue/cli-service/lib/config/base.js
  packages/@vue/cli-service/package.json
  yarn.lock
Labels: PR: New Feature
