Repository vuejs/vue-cli, pull requests merged in 2020-07, with the labels that each got.

#5629 refactor: replace jscodeshift with vue-codemod
  packages/@vue/cli-service/package.json
  packages/@vue/cli/lib/Generator.js
  packages/@vue/cli/lib/GeneratorAPI.js
  packages/@vue/cli/lib/util/runCodemod.js
  packages/@vue/cli/package.json
  yarn.lock
Labels: PR: Internal

#5658 fix(doc-zh): The link cannot be displayed correctly
  docs/zh/dev-guide/plugin-dev.md
Labels: PR: Documentation

#5664 Update Firebase project link
  docs/guide/deployment.md
Labels: PR: Documentation

#5665 feat: use Vue 3 JSX plugin if Vue 3 is detected in the project
  packages/@vue/babel-preset-app/README.md
  packages/@vue/babel-preset-app/index.js
  packages/@vue/babel-preset-app/package.json
  yarn.lock
Labels: PR: New Feature

#5671 docs(zh): change line to lines in plugin-dev.md
  docs/zh/dev-guide/plugin-dev.md
Labels: PR: Documentation

#5673 docs: additionalData option for sass-loader 9.0
  docs/guide/css.md
  docs/ru/guide/css.md
  docs/zh/guide/css.md
Labels: PR: Documentation

#5675 docs: extend the docs of babel-preset-app browserslist
  packages/@vue/babel-preset-app/README.md
Labels: PR: Documentation

#5356 feat(cli,cli-service,cli-test-utils): add ts declaration
  packages/@vue/cli-service/package.json
  packages/@vue/cli-service/types/ProjectOptions.d.ts
  packages/@vue/cli-service/types/cli-service-test.ts
  packages/@vue/cli-service/types/index.d.ts
  packages/@vue/cli-service/types/tsconfig.json
  packages/@vue/cli-test-utils/assertPromptModule.d.ts
  packages/@vue/cli-test-utils/createJSONServer.d.ts
  packages/@vue/cli-test-utils/createServer.d.ts
  packages/@vue/cli-test-utils/createTestProject.d.ts
  packages/@vue/cli-test-utils/generateWithPlugin.d.ts
  packages/@vue/cli-test-utils/launchPuppeteer.d.ts
  packages/@vue/cli-test-utils/package.json
  packages/@vue/cli-test-utils/serveWithPuppeteer.d.ts
  packages/@vue/cli-test-utils/types/cli-test-utils-test.ts
  packages/@vue/cli-test-utils/types/tsconfig.json
  packages/@vue/cli/package.json
  packages/@vue/cli/types/cli-test.ts
  packages/@vue/cli/types/index.d.ts
  packages/@vue/cli/types/tsconfig.json
  yarn.lock
Labels: PR: New Feature

#5679 docs: publicPath mistake of config reference
  docs/config/README.md
Labels: PR: Documentation

#5688 feat: add `skipLibCheck` option in the TS template (defaults to `true`)
  packages/@vue/cli-plugin-typescript/generator/template/tsconfig.json
  packages/@vue/cli-plugin-typescript/prompts.js
Labels: PR: New Feature

#5681 Fix Kubernetes container detection
  packages/@vue/cli-service/lib/commands/serve.js
Labels: PR: Bug Fix

#5700 refactor: use console.clear to clear the log
  packages/@vue/cli-shared-utils/lib/logger.js
Labels: PR: Internal

#5637 feat: allow choosing vue version on creation (and in presets)
  .eslintignore
  package.json
  packages/@vue/babel-preset-app/README.md
  packages/@vue/babel-preset-app/index.js
  packages/@vue/babel-preset-app/package.json
  packages/@vue/cli-plugin-babel/__tests__/babelMigrator.spec.js
  packages/@vue/cli-plugin-babel/__tests__/babelRuntime.spec.js
  packages/@vue/cli-plugin-babel/__tests__/transpileDependencies.spec.js
  packages/@vue/cli-plugin-eslint/__tests__/eslintMigrator.spec.js
  packages/@vue/cli-plugin-eslint/__tests__/eslintVue3.spec.js
  packages/@vue/cli-plugin-eslint/eslintDeps.js
  packages/@vue/cli-plugin-eslint/eslintOptions.js
  packages/@vue/cli-plugin-eslint/generator/index.js
  packages/@vue/cli-plugin-router/__tests__/routerGenerator.spec.js
  packages/@vue/cli-plugin-router/generator/index.js
  packages/@vue/cli-plugin-router/generator/injectUseRouter.js
  packages/@vue/cli-plugin-router/generator/template-vue3/src/router/index.js
  packages/@vue/cli-plugin-typescript/__tests__/tsPlugin.helper.js
  packages/@vue/cli-plugin-typescript/__tests__/tsPluginVue3.spec.js
  packages/@vue/cli-plugin-typescript/generator/index.js
  packages/@vue/cli-plugin-typescript/generator/template-vue3/src/App.vue
  packages/@vue/cli-plugin-typescript/generator/template-vue3/src/components/HelloWorld.vue
  packages/@vue/cli-plugin-typescript/generator/template-vue3/src/shims-vue.d.ts
  packages/@vue/cli-plugin-typescript/generator/template-vue3/src/views/Home.vue
  packages/@vue/cli-plugin-unit-jest/__tests__/jestPlugin.spec.js
  packages/@vue/cli-plugin-unit-jest/generator/index.js
  packages/@vue/cli-plugin-unit-jest/generator/template/tests/unit/example.spec.js
  packages/@vue/cli-plugin-unit-jest/generator/template/tests/unit/example.spec.ts
  packages/@vue/cli-plugin-unit-mocha/__tests__/mochaPlugin.spec.js
  packages/@vue/cli-plugin-unit-mocha/generator/index.js
  packages/@vue/cli-plugin-unit-mocha/generator/template/tests/unit/example.spec.js
  packages/@vue/cli-plugin-unit-mocha/generator/template/tests/unit/example.spec.ts
  packages/@vue/cli-plugin-unit-mocha/index.js
  packages/@vue/cli-plugin-vuex/__tests__/vuexGenerator.spec.js
  packages/@vue/cli-plugin-vuex/generator/index.js
  packages/@vue/cli-plugin-vuex/generator/injectUseStore.js
  packages/@vue/cli-plugin-vuex/generator/template-vue3/src/store/index.js
  packages/@vue/cli-service/__tests__/generator.spec.js
  packages/@vue/cli-service/__tests__/serve.spec.js
  packages/@vue/cli-service/__tests__/serveVue3.spec.js
  packages/@vue/cli-service/generator/index.js
  packages/@vue/cli-service/generator/template/src/main.js
  packages/@vue/cli-service/lib/config/base.js
  packages/@vue/cli-test-utils/assertPromptModule.js
  packages/@vue/cli-ui/apollo-server/connectors/projects.js
  packages/@vue/cli-ui/locales/en.json
  packages/@vue/cli-ui/tests/e2e/specs/g1-projects.js
  packages/@vue/cli/__tests__/Creator.spec.js
  packages/@vue/cli/__tests__/preset.spec.js
  packages/@vue/cli/lib/Creator.js
  packages/@vue/cli/lib/options.js
  packages/@vue/cli/lib/promptModules/vueVersion.js
  packages/@vue/cli/lib/util/ProjectPackageManager.js
  packages/@vue/cli/lib/util/createTools.js
  packages/@vue/cli/lib/util/features.js
  packages/@vue/cli/lib/util/inferRootOptions.js
  yarn.lock
Labels: PR: New Feature

#5722 fix: use fork-ts-checker-webpack-plugin v5 for vue 3 type checking
  packages/@vue/cli-plugin-typescript/index.js
  packages/@vue/cli-plugin-typescript/package.json
  yarn.lock
Labels: PR: Bug Fix

#5718 fix: make vue-loader-v16 an optional dependency, avoid crashing npm 5
  packages/@vue/cli-service/package.json
Labels: PR: Bug Fix

#5725 feat: implement a migrator that removes `vue-cli-plugin-next` as it's no longer needed
  packages/@vue/cli-service/migrator/index.js
Labels: PR: New Feature

#5479 feat(e2e-webdriverio): add e2e plugin for WebdriverIO
  docs/.vuepress/config.js
  docs/config/README.md
  docs/core-plugins/README.md
  docs/core-plugins/e2e-webdriverio.md
  packages/@vue/cli-plugin-e2e-webdriverio/.npmignore
  packages/@vue/cli-plugin-e2e-webdriverio/README.md
  packages/@vue/cli-plugin-e2e-webdriverio/__tests__/wdioPlugin.spec.js
  packages/@vue/cli-plugin-e2e-webdriverio/generator/index.js
  packages/@vue/cli-plugin-e2e-webdriverio/generator/template/logs/.gitkeep
  packages/@vue/cli-plugin-e2e-webdriverio/generator/template/tests/e2e/_eslintrc.js
  packages/@vue/cli-plugin-e2e-webdriverio/generator/template/tests/e2e/pageobjects/app.page.js
  packages/@vue/cli-plugin-e2e-webdriverio/generator/template/tests/e2e/specs/app.spec.js
  packages/@vue/cli-plugin-e2e-webdriverio/generator/template/wdio.local.conf.js
  packages/@vue/cli-plugin-e2e-webdriverio/generator/template/wdio.sauce.conf.js
  packages/@vue/cli-plugin-e2e-webdriverio/generator/template/wdio.shared.conf.js
  packages/@vue/cli-plugin-e2e-webdriverio/index.js
  packages/@vue/cli-plugin-e2e-webdriverio/package.json
  packages/@vue/cli-plugin-e2e-webdriverio/prompts.js
  packages/@vue/cli-plugin-e2e-webdriverio/ui.js
  packages/@vue/cli-shared-utils/lib/pluginResolution.js
  packages/@vue/cli/lib/promptModules/__tests__/e2e.spec.js
  packages/@vue/cli/lib/promptModules/e2e.js
  yarn.lock
Labels: PR: New Feature
