Repository vuejs/vue-cli, pull requests merged in 2020-01, with the labels that each got.

#5016 fix(e2e-nightwatch): check for correct flag name
  packages/@vue/cli-plugin-e2e-nightwatch/__tests__/nightwatchPlugin.spec.js
  packages/@vue/cli-plugin-e2e-nightwatch/index.js
Labels: PR: Bug Fix

#4910 fix: comment eslint disable in cypress config
  packages/@vue/cli-plugin-e2e-cypress/generator/template/tests/e2e/plugins/index.js
Labels: PR: Bug Fix

#5019 Updated zh-cn translation in cli section
  docs/zh/guide/cli-service.md
Labels: PR: Documentation

#4828 feat: add option merge to command create
  packages/@vue/cli/bin/vue.js
  packages/@vue/cli/lib/create.js
Labels: PR: New Feature

#5029 feat: don't throw on console/debugger statements for `vue serve`
  packages/@vue/cli-service-global/lib/globalConfigPlugin.js
Labels: PR: New Feature

#4959 feat: specify babel runtime version
  packages/@vue/babel-preset-app/index.js
Labels: PR: New Feature

#5051 docs(zh): Sync Chinese translation
  docs/zh/guide/css.md
Labels: PR: Documentation

#4827 feat: respect existing package.json
  packages/@vue/cli-service/lib/Service.js
  packages/@vue/cli-service/package.json
  packages/@vue/cli-shared-utils/index.js
  packages/@vue/cli-shared-utils/lib/pkg.js
  packages/@vue/cli-shared-utils/package.json
  packages/@vue/cli/lib/Creator.js
  yarn.lock
Labels: PR: New Feature

#4991 🎨 style: unified components' naming style
  packages/@vue/cli-plugin-router/generator/template/src/router/index.js
  packages/@vue/cli-plugin-router/generator/template/src/views/Home.vue
  packages/@vue/cli-plugin-typescript/generator/template/src/App.vue
  packages/@vue/cli-plugin-typescript/generator/template/src/views/Home.vue
  packages/@vue/cli-service/generator/template/src/App.vue
Labels: PR: Internal

#2411 feat(cli): add stdin flag to serve
  packages/@vue/cli-service/lib/commands/serve.js
Labels: PR: New Feature

#5069 Use a single websocket connection for HMR
  packages/@vue/cli-service/__tests__/serve.spec.js
  packages/@vue/cli-service/lib/commands/serve.js
  packages/@vue/cli-test-utils/launchPuppeteer.js
  packages/@vue/cli-test-utils/serveWithPuppeteer.js
Labels: PR: Bug Fix

#5038 fix: extendPackage object values should be string
  packages/@vue/cli/__tests__/Generator.spec.js
  packages/@vue/cli/lib/util/mergeDeps.js
Labels: PR: Bug Fix

#5062 fix `afterInvoke`/`onCreateComplete` callbacks in Migrator
  packages/@vue/cli/lib/Migrator.js
  packages/@vue/cli/lib/Upgrader.js
Labels: PR: Bug Fix

#5055 docs: mention the precedence of `.vue` & `.ts(x)` extensions
  docs/migrating-from-v3/README.md
Labels: PR: Documentation

#5045 refactor: use a plain http request to get package metadata
  packages/@vue/cli-shared-utils/lib/request.js
  packages/@vue/cli/lib/util/ProjectPackageManager.js
Labels: PR: Bug Fix

#5060 refactor: use the `title` option in the html template, instead of hard-code the project name
  packages/@vue/cli-service/generator/template/public/index.html
  packages/@vue/cli-service/lib/config/app.js
Labels: PR: Internal

#5078 Fix a typo in migration guide
  docs/migrating-from-v3/README.md
Labels: PR: Documentation

#5079 Mention that Vue CLI should be installed in Prototyping guide
  docs/guide/prototyping.md
Labels: PR: Documentation

#4933 feat: upgrade to eslint 6
  package.json
  packages/@vue/babel-preset-app/index.js
  packages/@vue/cli-plugin-e2e-nightwatch/__tests__/nightwatchPlugin.spec.js
  packages/@vue/cli-plugin-eslint/__tests__/eslintGenerator.spec.js
  packages/@vue/cli-plugin-eslint/eslintOptions.js
  packages/@vue/cli-plugin-eslint/generator/index.js
  packages/@vue/cli-plugin-pwa/lib/noopServiceWorker.js
  packages/@vue/cli-ui-addon-webpack/package.json
  packages/@vue/cli-ui-addon-webpack/src/mixins/Dashboard.js
  packages/@vue/cli-ui-addon-widgets/.eslintrc.js
  packages/@vue/cli-ui-addon-widgets/package.json
  packages/@vue/cli-ui-addon-widgets/src/components/News.vue
  packages/@vue/cli-ui-addon-widgets/src/components/Vulnerability.vue
  packages/@vue/cli-ui-addon-widgets/src/util/consts.js
  packages/@vue/cli-ui/apollo-server/api/PluginApi.js
  packages/@vue/cli-ui/apollo-server/connectors/client-addons.js
  packages/@vue/cli-ui/apollo-server/connectors/configurations.js
  packages/@vue/cli-ui/apollo-server/connectors/dependencies.js
  packages/@vue/cli-ui/apollo-server/connectors/git.js
  packages/@vue/cli-ui/apollo-server/connectors/plugins.js
  packages/@vue/cli-ui/apollo-server/connectors/progress.js
  packages/@vue/cli-ui/apollo-server/connectors/projects.js
  packages/@vue/cli-ui/apollo-server/connectors/prompts.js
  packages/@vue/cli-ui/apollo-server/connectors/shared-data.js
  packages/@vue/cli-ui/apollo-server/connectors/tasks.js
  packages/@vue/cli-ui/apollo-server/util/notification.js
  packages/@vue/cli-ui/apollo-server/util/parse-diff.js
  packages/@vue/cli-ui/apollo-server/util/terminate.js
  packages/@vue/cli-ui/package.json
  packages/@vue/cli-ui/src/components/content/TerminalView.vue
  packages/@vue/cli-ui/src/components/prompt/PromptCheckbox.vue
  packages/@vue/cli-ui/src/components/view/ViewNav.vue
  packages/@vue/cli-ui/src/i18n.js
  packages/@vue/cli-ui/tests/e2e/specs/g1-projects.js
  packages/@vue/cli-ui/ui-defaults/utils/audit.js
  packages/@vue/cli-ui/ui-defaults/utils/modules.js
  packages/@vue/cli/__tests__/invoke.spec.js
  packages/@vue/cli/lib/options.js
  yarn.lock
Labels: PR: New Feature

#5076 Add a demo for multiple loaders
  docs/guide/webpack.md
Labels: PR: Documentation

#5081 line 47 according to english version
  docs/zh/guide/browser-compatibility.md
Labels: PR: Documentation

#4953 feat: adds transparent PnP support to Webpack
  packages/@vue/cli-service/lib/config/base.js
  packages/@vue/cli-service/package.json
  yarn.lock
Labels: PR: New Feature

#5094 docs: [RU] Translation update
  docs/ru/guide/cli-service.md
  docs/ru/guide/prototyping.md
  docs/ru/guide/webpack.md
  docs/ru/migrating-from-v3/README.md
Labels: PR: Documentation

#5092 refactor: use createRequire to load/resolve modules
  packages/@vue/cli-shared-utils/lib/module.js
Labels: PR: Internal

#5110 refactor: use env variables to set registry for package managers
  packages/@vue/cli/lib/util/ProjectPackageManager.js
Labels: PR: Internal

#5028 fix applyESLint when eslint plugin is added after unit test plugins
  packages/@vue/cli-plugin-unit-jest/generator/index.js
  packages/@vue/cli-plugin-unit-mocha/__tests__/mochaGenerator.spec.js
  packages/@vue/cli-plugin-unit-mocha/generator/index.js
Labels: PR: Bug Fix

#5091 feat: `vue upgrade` monorepo support, `--from` option, and a new `vue migrate --from` command
  packages/@vue/cli/__tests__/Upgrader.spec.js
  packages/@vue/cli/__tests__/invoke.spec.js
  packages/@vue/cli/bin/vue.js
  packages/@vue/cli/lib/Migrator.js
  packages/@vue/cli/lib/MigratorAPI.js
  packages/@vue/cli/lib/Upgrader.js
  packages/@vue/cli/lib/invoke.js
  packages/@vue/cli/lib/migrate.js
  packages/@vue/cli/lib/util/ProjectPackageManager.js
  packages/@vue/cli/lib/util/getPkg.js
Labels: PR: New Feature

#4940 vue-cli@4 use core.js@^3.4.3
  docs/zh/guide/browser-compatibility.md
Labels: PR: Documentation

#5089 fix: pwa-plugin avoid generating manifest when path is an URL
  packages/@vue/cli-plugin-pwa/README.md
  packages/@vue/cli-plugin-pwa/lib/HtmlPwaPlugin.js
Labels: PR: Bug Fix

#5122 Add a demo for multiple loaders (Chinese doc)
  docs/zh/guide/webpack.md
Labels: PR: Documentation

#5113 fix: correctly calculate cacheIdentifier from lockfiles
  packages/@vue/cli-service/lib/PluginAPI.js
Labels: PR: Bug Fix

#5123 fix: vue-template-compiler can be optional if @vue/compiler-sfc presents
  packages/@vue/cli-service/lib/config/base.js
  packages/@vue/cli-service/package.json
Labels: PR: Internal
