Repository vuejs/vue-cli, pull requests merged in 2020-09, with the labels that each got.

#3687 perf(ui): improve get folder list to use Promises instead of sync
  packages/@vue/cli-ui/apollo-server/connectors/folders.js
Labels: PR: Internal

#5844 更新远程preset文档，与英文文档同步
  docs/zh/guide/plugins-and-presets.md
Labels: PR: Documentation

#5591 fix(unit-jest, unit-mocha): generate passing tests when `bare` option is used with router enabled (#3544)
  packages/@vue/cli-plugin-unit-jest/__tests__/jestGenerator.spec.js
  packages/@vue/cli-plugin-unit-jest/generator/index.js
  packages/@vue/cli-plugin-unit-jest/generator/template/tests/unit/example.spec.js
  packages/@vue/cli-plugin-unit-jest/generator/template/tests/unit/example.spec.ts
  packages/@vue/cli-plugin-unit-mocha/__tests__/mochaGenerator.spec.js
  packages/@vue/cli-plugin-unit-mocha/generator/index.js
  packages/@vue/cli-plugin-unit-mocha/generator/template/tests/unit/example.spec.js
  packages/@vue/cli-plugin-unit-mocha/generator/template/tests/unit/example.spec.ts
Labels: PR: Bug Fix

#5852 fix: fix duplicate id="app" in Vue 3 project template
  packages/@vue/cli-plugin-router/__tests__/routerGenerator.spec.js
  packages/@vue/cli-plugin-router/generator/template-vue3/src/App.vue
  packages/@vue/cli-service/__tests__/generator.spec.js
  packages/@vue/cli-service/generator/index.js
  packages/@vue/cli-service/generator/template/src/App.vue
  packages/@vue/cli-service/generator/template/src/main.js
Labels: PR: Bug Fix

#5868 fix: enable some syntax extensions by default for vue script compiler
  packages/@vue/cli-service/lib/config/base.js
  packages/@vue/cli-service/package.json
  yarn.lock
Labels: PR: Bug Fix

#5065 Remove linter option TSLint
  docs/core-plugins/typescript.md
  docs/ru/core-plugins/typescript.md
  packages/@vue/cli-plugin-e2e-cypress/__tests__/cypressPlugin.spec.js
  packages/@vue/cli-plugin-e2e-webdriverio/__tests__/wdioPlugin.spec.js
  packages/@vue/cli-plugin-typescript/README.md
  packages/@vue/cli-plugin-typescript/__tests__/tsConvertLintFlags.spec.js
  packages/@vue/cli-plugin-typescript/__tests__/tsGenerator.spec.js
  packages/@vue/cli-plugin-typescript/__tests__/tsPluginTSLint.spec.js
  packages/@vue/cli-plugin-typescript/generator/convert.js
  packages/@vue/cli-plugin-typescript/generator/index.js
  packages/@vue/cli-plugin-typescript/generator/template/src/shims-tsx.d.ts
  packages/@vue/cli-plugin-typescript/generator/template/tslint.json
  packages/@vue/cli-plugin-typescript/index.js
  packages/@vue/cli-plugin-typescript/lib/convertLintFlags.js
  packages/@vue/cli-plugin-typescript/lib/tslint.js
  packages/@vue/cli-plugin-typescript/package.json
  packages/@vue/cli-plugin-typescript/prompts.js
  packages/@vue/cli/lib/promptModules/__tests__/typescript.spec.js
  packages/@vue/cli/lib/promptModules/linter.js
  packages/@vue/cli/lib/promptModules/typescript.js
  yarn.lock
Labels: PR: Breaking Change

#5869 fix: skip checking git gpgSign config
  packages/@vue/cli/lib/Creator.js
Labels: PR: Bug Fix

#5870 chore!: update eslint-loader, minimum supported ESLint version is 6
  docs/migrations/migrate-from-v4.md
  packages/@vue/cli-plugin-eslint/__tests__/eslintMigrator.spec.js
  packages/@vue/cli-plugin-eslint/migrator/index.js
  packages/@vue/cli-plugin-eslint/package.json
  packages/@vue/cli-service-global/package.json
  yarn.lock
Labels: PR: Breaking Change

#5885 Docs: Update en.json
  packages/@vue/cli-ui/locales/en.json
Labels: PR: Documentation

#5892 fix: respect scope when resolving package metadata
  packages/@vue/cli/lib/util/ProjectPackageManager.js
Labels: PR: Bug Fix

#5883 In build-targets.md add "using vuex"
  docs/zh/guide/build-targets.md
Labels: PR: Documentation

#5899 fix: shouldn't remove attribute quotes in HTML
  packages/@vue/cli-plugin-pwa/__tests__/pwaPlugin.spec.js
  packages/@vue/cli-service/__tests__/build.spec.js
  packages/@vue/cli-service/__tests__/cors.spec.js
  packages/@vue/cli-service/__tests__/modernMode.spec.js
  packages/@vue/cli-service/__tests__/multiPage.spec.js
  packages/@vue/cli-service/lib/config/app.js
Labels: PR: Bug Fix

#5884 docs: add yarn link error solution
  .github/CONTRIBUTING.md
Labels: PR: Documentation

#5902 fix: incorrectly read Taobao binary mirror configuration.
  packages/@vue/cli/lib/util/ProjectPackageManager.js
Labels: PR: Bug Fix

#5847 Updated netlify docs for vue/cli-plugin-pwa
  docs/guide/deployment.md
Labels: PR: Documentation

#3797 docs: add notes on the `vue inspect` command
  docs/guide/webpack.md
Labels: PR: Documentation

#5871 fix: more accurate warning message for missing global peer dependencies
  packages/@vue/cli/lib/util/clearConsole.js
  packages/@vue/cli/lib/util/getGlobalInstallCommand.js
  packages/@vue/cli/lib/util/loadCommand.js
Labels: PR: Bug Fix

#5906 chore: show error message that the `wc` target with Vue 3 isn't supported yet
  packages/@vue/cli-service/lib/commands/build/resolveWcConfig.js
Labels: PR: Polish

#5907 chore!: bump unit-mocha dependency versions
  docs/migrations/migrate-from-v4.md
  packages/@vue/cli-plugin-unit-mocha/generator/index.js
  packages/@vue/cli-plugin-unit-mocha/package.json
  yarn.lock
Labels: PR: Breaking Change, PR: Underlying Tools

#5903 fix: update the `.vue` file shim for Vue 3
  packages/@vue/cli-plugin-babel/package.json
  packages/@vue/cli-plugin-typescript/codemods/__testfixtures__/shims-vue.input.ts
  packages/@vue/cli-plugin-typescript/codemods/__testfixtures__/shims-vue.output.ts
  packages/@vue/cli-plugin-typescript/codemods/__tests__/migrateComponentType.spec.js
  packages/@vue/cli-plugin-typescript/codemods/migrateComponentType.js
  packages/@vue/cli-plugin-typescript/generator/template-vue3/src/shims-vue.d.ts
  packages/@vue/cli-plugin-typescript/migrator/index.js
  packages/@vue/cli-plugin-typescript/package.json
  packages/@vue/cli-service/__tests__/generator.spec.js
  packages/@vue/cli-service/generator/index.js
  yarn.lock
Labels: PR: Bug Fix
