Repository vuejs/vue-cli, pull requests merged in 2021-08, with the labels that each got.

#6625 feat(unit-jest): add jest as a peer dependency
  packages/@vue/cli-plugin-unit-jest/generator/index.js
  packages/@vue/cli-plugin-unit-jest/migrator/index.js
  packages/@vue/cli-plugin-unit-jest/package.json
Labels: PR: New Feature

#6623 fix(docs): the plugin-dev in zh has a regexp lose the end /
  docs/zh/dev-guide/plugin-dev.md
Labels: PR: Documentation

#6635 fix(ui): stop depending on the `watch` package
  packages/@vue/cli-ui/apollo-server/connectors/locales.js
  packages/@vue/cli-ui/package.json
  yarn.lock
Labels: PR: Internal

#6645 fix(cli-service): wrong property name (typo)
  packages/@vue/cli-service/lib/commands/build/resolveAppConfig.js
Labels: PR: Bug Fix

#6620 Fix typo in deployment guide
  docs/guide/deployment.md
Labels: PR: Documentation

#6642 docs: Update README.md
  docs/zh/guide/README.md
Labels: PR: Documentation

#6653 docs: recommend SFC playground and StackBlitz for instant prototyping
  docs/migrations/migrate-from-v4.md
Labels: PR: Documentation

#6638 refactor: remove redundant Webpack version checks
  packages/@vue/cli-plugin-pwa/lib/HtmlPwaPlugin.js
  packages/@vue/cli-service/lib/commands/build/resolveWcConfig.js
  packages/@vue/cli-service/lib/config/app.js
  packages/@vue/cli-service/lib/config/base.js
Labels: PR: Internal
