Repository vuejs/vue-cli, pull requests merged in 2021-11, with the labels that each got.

#6795 feat(generator)!: bump eslint-plugin-vue to v8
  docs/migrations/migrate-from-v4.md
  package.json
  packages/@vue/cli-plugin-eslint/eslintDeps.js
  packages/@vue/cli-ui-addon-webpack/package.json
  packages/@vue/cli-ui-addon-webpack/src/main.js
  packages/@vue/cli-ui-addon-widgets/package.json
  packages/@vue/cli-ui-addon-widgets/src/main.js
  packages/@vue/cli-ui/package.json
  yarn.lock
Labels: PR: New Feature

#6809 refactor: use multi-word names for router views
  packages/@vue/cli-plugin-router/__tests__/routerGenerator.spec.js
  packages/@vue/cli-plugin-router/generator/template-vue3/src/router/index.js
  packages/@vue/cli-plugin-router/generator/template/src/router/index.js
  packages/@vue/cli-plugin-router/generator/template/src/views/AboutView.vue
  packages/@vue/cli-plugin-router/generator/template/src/views/HomeView.vue
  packages/@vue/cli-plugin-typescript/__tests__/tsGenerator.spec.js
  packages/@vue/cli-plugin-typescript/generator/template-vue3/src/views/HomeView.vue
  packages/@vue/cli-plugin-typescript/generator/template/src/views/HomeView.vue
  packages/@vue/cli-ui-addon-webpack/.eslintrc.js
  packages/@vue/cli-ui-addon-widgets/.eslintrc.js
  packages/@vue/cli-ui/.eslintrc.js
Labels: PR: Internal

#6808 feat!: remove `@vue/compiler-sfc` from peer dependencies
  packages/@vue/babel-preset-app/package.json
  packages/@vue/cli-plugin-typescript/index.js
  packages/@vue/cli-plugin-typescript/package.json
  packages/@vue/cli-service/__tests__/generator.spec.js
  packages/@vue/cli-service/generator/index.js
  packages/@vue/cli-service/lib/config/base.js
  packages/@vue/cli-service/package.json
Labels: PR: Breaking Change

#6817 feat: generate `vue.config.js` with `defineConfig` wrapper
  packages/@vue/cli/__tests__/Generator.spec.js
  packages/@vue/cli/lib/util/__tests__/extendJSConfig.spec.js
  packages/@vue/cli/lib/util/configTransforms.js
  packages/@vue/cli/lib/util/extendJSConfig.js
Labels: PR: New Feature

#6824 feat: update npm.taobao.org to npmmirror.com
  docs/guide/creating-a-project.md
  docs/ru/guide/creating-a-project.md
  docs/zh/guide/creating-a-project.md
  packages/@vue/cli/lib/util/registries.js
Labels: PR: New Feature

#6829 fix: require webpack 5.54+
  package.json
  packages/@vue/cli-plugin-babel/package.json
  packages/@vue/cli-plugin-eslint/package.json
  packages/@vue/cli-plugin-pwa/package.json
  packages/@vue/cli-plugin-typescript/package.json
  packages/@vue/cli-service/package.json
  yarn.lock
Labels: PR: Bug Fix

#6826 fix: [ext] in asset modules already contains a leading dot
  packages/@vue/cli-service/lib/config/assets.js
Labels: PR: Bug Fix
