Repository vuejs/vue-cli, pull requests merged in 2021-07, with the labels that each got.

#6560 fix(mocha): do not ignore JavaScript tests when TypeScript plugin is installed
  packages/@vue/cli-plugin-unit-mocha/index.js
Labels: PR: Bug Fix

#6589 Fix command description typo
  packages/@vue/cli/bin/vue.js
Labels: PR: Documentation

#6598 chore!: drop webpack-4 support in v5
  .circleci/config.yml
  docs/core-plugins/webpack-4.md
  docs/migrations/migrate-from-v4.md
  jest.config.js
  packages/@vue/cli-plugin-webpack-4/README.md
  packages/@vue/cli-plugin-webpack-4/generator.js
  packages/@vue/cli-plugin-webpack-4/index.js
  packages/@vue/cli-plugin-webpack-4/package.json
  packages/@vue/cli-service/lib/Service.js
  packages/@vue/cli-service/lib/util/checkWebpack.js
  packages/@vue/cli-service/package.json
  scripts/test.js
Labels: PR: Breaking Change

#6597 fix: mark `sideEffects: true` for styles in Vue components
  packages/@vue/cli-service/lib/config/base.js
Labels: PR: Bug Fix
