Repository vuejs/vue-cli, pull requests merged in 2021-05, with the labels that each got.

#6455 fix(v4): get rid of ssri vulnerability warnings
  packages/@vue/cli-service/package.json
  yarn.lock
Labels: PR: Bug Fix

#6454 fix: fix jest migrator dependency merging
  packages/@vue/cli-plugin-unit-jest/migrator/index.js
Labels: PR: Bug Fix

#6443 fix!: keep project name validation rules in sync between UI and CLI
  packages/@vue/cli-ui/apollo-server/connectors/projects.js
  packages/@vue/cli-ui/package.json
  packages/@vue/cli-ui/src/components/project-create/ProjectCreate.vue
Labels: PR: Breaking Change, PR: Bug Fix

#6456 fix(typescript): add missing dependencies and `require.resolve` compiler
  packages/@vue/cli-plugin-typescript/index.js
  packages/@vue/cli-plugin-typescript/package.json
Labels: PR: Bug Fix

#6459 fix(v4): fix modern mode optional chaining syntax tranpilation
  packages/@vue/babel-preset-app/index.js
Labels: PR: Bug Fix

#6377 replace master with main to reflect GH default
  docs/guide/deployment.md
Labels: PR: Documentation

#6471 feat: support webpack 5 in unit-mocha plugin
  packages/@vue/cli-plugin-unit-mocha/generator/index.js
  packages/@vue/cli-plugin-unit-mocha/package.json
  yarn.lock
Labels: PR: New Feature

#6472 Feature: add "tags" part to htmlWebpackPlugin
  packages/@vue/cli-service/lib/config/app.js
Labels: PR: New Feature

#6470 fix(SafariNomoduleFixPlugin): use RawSource instead of a plain object
  packages/@vue/cli-service/lib/webpack/SafariNomoduleFixPlugin.js
  packages/@vue/cli-service/package.json
Labels: PR: Bug Fix
