Repository vuejs/vue-cli, pull requests merged in 2021-09, with the labels that each got.

#6662 feat!: update cypress to 8.3 and require it to be a peer dependency
  docs/migrations/migrate-from-v4.md
  packages/@vue/cli-plugin-e2e-cypress/generator/index.js
  packages/@vue/cli-plugin-e2e-cypress/migrator/index.js
  packages/@vue/cli-plugin-e2e-cypress/package.json
  yarn.lock
Labels: PR: Breaking Change, PR: New Feature

#6665 fix: avoid copy-webpack plugin errors in module mode
  packages/@vue/cli-service/lib/config/app.js
Labels: PR: Bug Fix

#6663 feat: generate projects with `transpileDependencies: true` by default
  packages/@vue/cli-plugin-babel/__tests__/transpileDependencies.spec.js
  packages/@vue/cli-plugin-babel/generator.js
  packages/@vue/cli-plugin-eslint/__tests__/eslintGenerator.spec.js
Labels: PR: New Feature

#6669 feat!: upgrade to webpack-dev-server v4
  docs/migrations/migrate-from-v4.md
  packages/@vue/cli-plugin-eslint/__tests__/eslintPlugin.spec.js
  packages/@vue/cli-service/__tests__/multiPage.spec.js
  packages/@vue/cli-service/__tests__/serve.spec.js
  packages/@vue/cli-service/lib/commands/serve.js
  packages/@vue/cli-service/package.json
  packages/@vue/cli-test-utils/launchPuppeteer.js
  yarn.lock
Labels: PR: Breaking Change, PR: New Feature

#6627 feat: update jest to v27
  docs/migrations/migrate-from-v4.md
  package.json
  packages/@vue/cli-plugin-typescript/package.json
  packages/@vue/cli-plugin-unit-jest/__tests__/jestPlugin.spec.js
  packages/@vue/cli-plugin-unit-jest/__tests__/jestPluginVue3.spec.js
  packages/@vue/cli-plugin-unit-jest/generator/index.js
  packages/@vue/cli-plugin-unit-jest/migrator/index.js
  packages/@vue/cli-plugin-unit-jest/package.json
  packages/@vue/cli-plugin-unit-jest/presets/default/jest-preset.js
  packages/@vue/cli-plugin-unit-jest/presets/no-babel/esmoduleTransformer.js
  yarn.lock
Labels: PR: Breaking Change, PR: New Feature

#6695 refactor(webdriverio)!: don't include sync API support by default
  packages/@vue/cli-plugin-e2e-webdriverio/generator/template/tests/e2e/pageobjects/app.page.js
  packages/@vue/cli-plugin-e2e-webdriverio/generator/template/tests/e2e/specs/app.spec.js
  packages/@vue/cli-plugin-e2e-webdriverio/index.js
  packages/@vue/cli-plugin-e2e-webdriverio/migrator/index.js
  packages/@vue/cli-plugin-e2e-webdriverio/package.json
Labels: PR: Breaking Change

#6706 docs: update vue create --help output in "Basics/Creating a Project"
  docs/guide/creating-a-project.md
Labels: PR: Documentation
