Repository vuejs/vue-cli, pull requests merged in 2021-02, with the labels that each got.

#6266 Add note about loader incompatible with webpack 4
  docs/guide/css.md
Labels: PR: Documentation

#6269 feat: use html-webpack-plugin v5 by default
  docs/migrations/migrate-from-v4.md
  packages/@vue/cli-plugin-babel/index.js
  packages/@vue/cli-plugin-pwa/package.json
  packages/@vue/cli-plugin-webpack-4/generator.js
  packages/@vue/cli-plugin-webpack-4/index.js
  packages/@vue/cli-plugin-webpack-4/package.json
  packages/@vue/cli-service/__tests__/build.spec.js
  packages/@vue/cli-service/__tests__/cors.spec.js
  packages/@vue/cli-service/__tests__/modernMode.spec.js
  packages/@vue/cli-service/lib/Service.js
  packages/@vue/cli-service/lib/config/app.js
  packages/@vue/cli-service/lib/webpack/ModernModePlugin.js
  packages/@vue/cli-service/package.json
  scripts/test.js
  yarn.lock
Labels: PR: Breaking Change, PR: New Feature

#6279 feat!: update copy & terser plugin, move more legacy code to webpack-4 plugin
  docs/migrations/migrate-from-v4.md
  packages/@vue/cli-plugin-webpack-4/index.js
  packages/@vue/cli-plugin-webpack-4/package.json
  packages/@vue/cli-service/lib/config/app.js
  packages/@vue/cli-service/lib/config/base.js
  packages/@vue/cli-service/lib/config/prod.js
  packages/@vue/cli-service/lib/config/terserOptions.js
  packages/@vue/cli-service/package.json
  yarn.lock
Labels: PR: Breaking Change, PR: New Feature

#6277 fix(cli-plugin-pwa): webpack5 warning for emitting manifest.json
  packages/@vue/cli-plugin-pwa/lib/HtmlPwaPlugin.js
Labels: PR: Bug Fix

#6291 fix: better dev server & webpack 4 compatibility and some trivial dependency updates
  package.json
  packages/@vue/babel-preset-app/package.json
  packages/@vue/cli-plugin-babel/generator.js
  packages/@vue/cli-plugin-babel/migrator/index.js
  packages/@vue/cli-plugin-babel/package.json
  packages/@vue/cli-plugin-e2e-cypress/package.json
  packages/@vue/cli-plugin-e2e-nightwatch/package.json
  packages/@vue/cli-plugin-e2e-webdriverio/package.json
  packages/@vue/cli-plugin-eslint/eslintDeps.js
  packages/@vue/cli-plugin-eslint/generator/index.js
  packages/@vue/cli-plugin-eslint/migrator/index.js
  packages/@vue/cli-plugin-eslint/package.json
  packages/@vue/cli-plugin-pwa/package.json
  packages/@vue/cli-plugin-router/generator/index.js
  packages/@vue/cli-plugin-typescript/package.json
  packages/@vue/cli-plugin-unit-jest/generator/index.js
  packages/@vue/cli-plugin-unit-jest/package.json
  packages/@vue/cli-plugin-unit-mocha/generator/index.js
  packages/@vue/cli-plugin-unit-mocha/package.json
  packages/@vue/cli-plugin-vuex/generator/index.js
  packages/@vue/cli-plugin-webpack-4/index.js
  packages/@vue/cli-plugin-webpack-4/package.json
  packages/@vue/cli-service/generator/index.js
  packages/@vue/cli-service/lib/util/checkWebpack.js
  packages/@vue/cli-service/package.json
  packages/@vue/cli-shared-utils/package.json
  packages/@vue/cli-test-utils/package.json
  packages/@vue/cli-ui-addon-webpack/package.json
  packages/@vue/cli-ui-addon-widgets/package.json
  packages/@vue/cli-ui/package.json
  packages/@vue/cli-ui/src/style/main.styl
  packages/@vue/cli/package.json
  yarn.lock
Labels: PR: Bug Fix

#6292 chore!: drop Node.js v10 support
  appveyor.yml
  packages/@vue/cli-service/package.json
  packages/@vue/cli-ui/package.json
  packages/@vue/cli/package.json
Labels: PR: Breaking Change

#6295 feat!: update WebDriverIO to v7
  docs/migrations/migrate-from-v4.md
  packages/@vue/cli-plugin-e2e-webdriverio/__tests__/wdioGenerator.spec.js
  packages/@vue/cli-plugin-e2e-webdriverio/generator/index.js
  packages/@vue/cli-plugin-e2e-webdriverio/generator/template/wdio.shared.conf.js
  packages/@vue/cli-plugin-e2e-webdriverio/migrator/index.js
  packages/@vue/cli-plugin-e2e-webdriverio/package.json
  packages/@vue/cli-plugin-typescript/generator/template/tsconfig.json
Labels: PR: Breaking Change, PR: New Feature

#6301 feat!: use the latest versions of css preprocessor loaders by default
  docs/migrations/migrate-from-v4.md
  packages/@vue/cli-plugin-webpack-4/generator.js
  packages/@vue/cli-plugin-webpack-4/index.js
  packages/@vue/cli-plugin-webpack-4/package.json
  packages/@vue/cli-service/generator/index.js
Labels: PR: Breaking Change, PR: New Feature

#6300 chore: remove the word "Preview" from vue 3 preset
  packages/@vue/cli-ui/apollo-server/connectors/projects.js
  packages/@vue/cli-ui/locales/en.json
  packages/@vue/cli/__tests__/Creator.spec.js
  packages/@vue/cli/lib/Creator.js
Labels: PR: Polish

#6303 fix(create): write the lint-staged config to its own file (close #6298)
  packages/@vue/cli/lib/Generator.js
Labels: PR: Bug Fix

#6304 fix(generator): support npm package aliases ("@npm:" in version specifier)
  packages/@vue/cli/__tests__/Generator.spec.js
  packages/@vue/cli/lib/util/mergeDeps.js
Labels: PR: Bug Fix

#6254 fix: correctly pad log strings
  packages/@vue/cli-shared-utils/lib/logger.js
Labels: PR: Bug Fix

#6307 feat(GeneratorAPI): `forceOverwrite` option for `extendPackage`
  packages/@vue/cli-plugin-webpack-4/generator.js
  packages/@vue/cli/__tests__/Generator.spec.js
  packages/@vue/cli/lib/GeneratorAPI.js
  packages/@vue/cli/lib/util/mergeDeps.js
  packages/@vue/cli/types/cli-test.ts
  packages/@vue/cli/types/index.d.ts
Labels: PR: New Feature

#6309 fix(webdriverio): add `expect-webdriverio` to tsconfig
  packages/@vue/cli-plugin-e2e-webdriverio/migrator/index.js
  packages/@vue/cli-plugin-typescript/generator/template/tsconfig.json
Labels: PR: Bug Fix
