Repository vuejs/vue-cli, pull requests merged in 2021-04, with the labels that each got.

#5997 feat(cli-service): add inline loader support for html-webpack-plugin
  packages/@vue/cli-service/lib/config/app.js
Labels: PR: New Feature

#6400 fix(mocha): workaround the SVGElement issue in Vue
  packages/@vue/cli-plugin-unit-mocha/setup.js
Labels: PR: Bug Fix

#6402 fix(cli-service): respect the existing 'devtool'
  packages/@vue/cli-service/lib/commands/serve.js
Labels: PR: Bug Fix

#6401 chore: de-prioritize "Mocha + Chai" option as it requires webpack 4 for now
  packages/@vue/cli/lib/promptModules/__tests__/unit.spec.js
  packages/@vue/cli/lib/promptModules/unit.js
Labels: PR: Polish

#6285 feat(cli-service): provide jsconfig.json in no-ts template
  packages/@vue/cli-service/generator/index.js
  packages/@vue/cli-service/generator/template/jsconfig.json
Labels: PR: New Feature

#6405 feat: support `vue.config.mjs`
  package.json
  packages/@vue/cli-plugin-typescript/__tests__/tsPluginBabel.spec.js
  packages/@vue/cli-service/__tests__/Service.spec.js
  packages/@vue/cli-service/__tests__/ServiceESM.spec.js
  packages/@vue/cli-service/__tests__/css.spec.js
  packages/@vue/cli-service/lib/Service.js
  packages/@vue/cli-service/lib/util/checkWebpack.js
  packages/@vue/cli-service/lib/util/loadFileConfig.js
  packages/@vue/cli-service/lib/util/resolveUserConfig.js
  packages/@vue/cli-service/package.json
  yarn.lock
Labels: PR: New Feature

#6416 feat!: turn on modern mode by default, and provide a `--no-module` option
  packages/@vue/cli-plugin-babel/__tests__/transpileDependencies.spec.js
  packages/@vue/cli-service/__tests__/build.spec.js
  packages/@vue/cli-service/__tests__/cors.spec.js
  packages/@vue/cli-service/__tests__/cssPreprocessors.spec.js
  packages/@vue/cli-service/__tests__/modernMode.spec.js
  packages/@vue/cli-service/__tests__/multiPage.spec.js
  packages/@vue/cli-service/lib/commands/build/index.js
  packages/@vue/cli-service/lib/commands/build/resolveAppConfig.js
  packages/@vue/cli-service/lib/util/targets.js
  packages/@vue/cli-service/lib/webpack/ModernModePlugin.js
  packages/@vue/cli-service/package.json
  packages/@vue/cli-ui/src/components/content/TerminalView.vue
  packages/@vue/cli-ui/ui-defaults/tasks.js
Labels: PR: Breaking Change, PR: New Feature

#6418 Show fallback message for typescript jest preset if ts-jest is not in…
  packages/@vue/cli-plugin-unit-jest/presets/typescript/jest-preset.js
Labels: PR: Bug Fix

#6419 feat: only needs one bundle if all targets support es module
  packages/@vue/babel-preset-app/index.js
  packages/@vue/cli-service/__tests__/modernMode.spec.js
  packages/@vue/cli-service/bin/vue-cli-service.js
  packages/@vue/cli-service/lib/commands/build/index.js
  packages/@vue/cli-service/lib/commands/build/resolveAppConfig.js
  packages/@vue/cli-service/lib/util/targets.js
  packages/@vue/cli-service/lib/webpack/DashboardPlugin.js
  packages/@vue/cli-service/lib/webpack/ModernModePlugin.js
  packages/@vue/cli-service/lib/webpack/SafariNomoduleFixPlugin.js
Labels: PR: New Feature

#6422 feat!: always inject safari-nomodule-fix as an external script; drop `--no-unsafe-inline` flag
  docs/guide/browser-compatibility.md
  docs/guide/cli-service.md
  docs/zh/guide/browser-compatibility.md
  packages/@vue/cli-service/__tests__/modernMode.spec.js
  packages/@vue/cli-service/lib/commands/build/index.js
  packages/@vue/cli-service/lib/commands/build/resolveAppConfig.js
Labels: PR: Breaking Change, PR: New Feature

#6413 chore(cli): rely on default arg parser behaviour
  packages/@vue/cli/bin/vue.js
Labels: PR: Polish

#6420 feat!: upgrade to css-minimizer-webpack-plugin v2
  packages/@vue/cli-plugin-webpack-4/index.js
  packages/@vue/cli-plugin-webpack-4/package.json
  packages/@vue/cli-service/lib/config/css.js
  packages/@vue/cli-service/package.json
  yarn.lock
Labels: PR: Breaking Change, PR: New Feature

#6359 Fix master to main in heroku deployment
  docs/guide/deployment.md
Labels: PR: Documentation

#6430 chore: some dependency version bumps
  docs/migrations/migrate-from-v4.md
  package.json
  packages/@vue/cli-plugin-babel/package.json
  packages/@vue/cli-plugin-e2e-cypress/package.json
  packages/@vue/cli-plugin-e2e-nightwatch/package.json
  packages/@vue/cli-plugin-e2e-webdriverio/package.json
  packages/@vue/cli-plugin-typescript/package.json
  yarn.lock
Labels: PR: Polish

#6428 feat(plugin-typescript): add all recommended tsconfig
  packages/@vue/cli-plugin-typescript/generator/template/tsconfig.json
Labels: PR: New Feature

#6437 fix: should not include IE11 target in Vue 3 projects
  packages/@vue/cli-service/generator/index.js
Labels: PR: Bug Fix

#6439 feat!: drop IE11 support in CLI UI
  packages/@vue/cli-ui-addon-webpack/package.json
  packages/@vue/cli-ui-addon-widgets/.browserslistrc
  packages/@vue/cli-ui/package.json
Labels: PR: Breaking Change

#6440 fix(ui): fix publicPath documentation link
  packages/@vue/cli-ui/ui-defaults/config.js
Labels: PR: Bug Fix

#6438 docs: add modern mode changes to the migration guide
  docs/migrations/migrate-from-v4.md
Labels: PR: Documentation

#6446 ci: fix random failing ui tests
  .circleci/config.yml
  packages/@vue/cli-ui/tests/e2e/specs/g1-projects.js
  packages/@vue/cli-ui/tests/e2e/specs/g2-plugins.js
  packages/@vue/cli-ui/tests/e2e/support/index.js
Labels: PR: Internal
