Repository vuejs/vue-cli, pull requests merged in 2021-03, with the labels that each got.

#6332 feat!: upgrade to css-loader 5; remove `css.requireModuleExtension` & `css.modules` options
  docs/config/README.md
  docs/guide/css.md
  docs/migrations/migrate-from-v4.md
  packages/@vue/cli-service/__tests__/css.spec.js
  packages/@vue/cli-service/lib/Service.js
  packages/@vue/cli-service/lib/config/css.js
  packages/@vue/cli-service/lib/options.js
  packages/@vue/cli-service/package.json
  yarn.lock
Labels: PR: Breaking Change, PR: New Feature

#6314 fix: fix `build --dest` option
  packages/@vue/cli-service/__tests__/build.spec.js
  packages/@vue/cli-service/lib/commands/build/resolveAppConfig.js
Labels: PR: Bug Fix

#6335 chore!: update vue-jest to v4.x
  packages/@vue/cli-plugin-unit-jest/__tests__/jestPlugin.spec.js
  packages/@vue/cli-plugin-unit-jest/package.json
  packages/@vue/cli-plugin-unit-jest/presets/no-babel/jest-preset.js
  yarn.lock
Labels: PR: Breaking Change, PR: New Feature

#6343 fix: use cssnano v5.0.0-rc.1, work around a npm 6 hoisting bug
  packages/@vue/cli-service/package.json
  yarn.lock
Labels: PR: Bug Fix

#6347 refactor!: move vue-jest and ts-jest to peer dependencies
  docs/migrations/migrate-from-v4.md
  packages/@vue/cli-plugin-unit-jest/generator/index.js
  packages/@vue/cli-plugin-unit-jest/migrator/index.js
  packages/@vue/cli-plugin-unit-jest/package.json
Labels: PR: Breaking Change

#6348 chore!: bump copy-webpack-plugin to v8
  docs/migrations/migrate-from-v4.md
  packages/@vue/cli-service/package.json
  yarn.lock
Labels: PR: Breaking Change

#6366 fix(build): demo-lib.html compatible Vue 3
  packages/@vue/cli-service/lib/commands/build/demo-lib.html
  packages/@vue/cli-service/lib/commands/build/resolveLibConfig.js
Labels: PR: Bug Fix

#6358 fix: work around npm6/postcss8 hoisting issue
  packages/@vue/cli-service/bin/postinstall.js
  packages/@vue/cli-service/generator/hotfix-npm6only.js
  packages/@vue/cli-service/generator/index.js
  packages/@vue/cli-service/package.json
Labels: PR: Bug Fix

#6355 feat: a `defineConfig` API from `@vue/cli-service` for better typing support in `vue.config.js`
  docs/config/README.md
  docs/zh/config/README.md
  packages/@vue/cli-service/lib/Service.js
  packages/@vue/cli-service/types/index.d.ts
Labels: PR: New Feature

#6354 feat: when `transpileDependencies` is set to `true`, transpile all dependencies in `node_modules`
  docs/config/README.md
  docs/core-plugins/babel.md
  docs/migrations/migrate-from-v4.md
  docs/zh/config/README.md
  packages/@vue/cli-plugin-babel/__tests__/babelRuntime.spec.js
  packages/@vue/cli-plugin-babel/__tests__/transpileDependencies.spec.js
  packages/@vue/cli-plugin-babel/index.js
  packages/@vue/cli-service/lib/options.js
  packages/@vue/cli-service/types/ProjectOptions.d.ts
Labels: PR: New Feature

#6372 fix: check hoisted postcss version
  packages/@vue/cli-service/bin/postinstall.js
  packages/@vue/cli-service/generator/hotfix-npm6only.js
  packages/@vue/cli-service/generator/index.js
  packages/@vue/cli-service/lib/config/css.js
  packages/@vue/cli-service/package.json
Labels: PR: Bug Fix
