Repository vuejs/vue-cli, pull requests merged in 2021-06, with the labels that each got.

#6478 fix(mocha): set mode to `none` to avoid DefinePlugin conflict
  packages/@vue/cli-plugin-unit-mocha/index.js
Labels: PR: Bug Fix

#6506 fix(webpack): slash on publicPath: 'auto'
  packages/@vue/cli-service/lib/util/resolveUserConfig.js
Labels: PR: Bug Fix

#6487 update deployment.md
  docs/zh/guide/deployment.md
Labels: PR: Documentation

#6493 Fixed some minor typos
  docs/guide/deployment.md
Labels: PR: Documentation

#6411 feat: implement plugin execution order
  packages/@vue/cli-plugin-typescript/__tests__/tsGenerator.spec.js
  packages/@vue/cli-plugin-typescript/generator/index.js
  packages/@vue/cli-service/__tests__/Service.spec.js
  packages/@vue/cli-service/lib/Service.js
  packages/@vue/cli-shared-utils/__tests__/pluginOrder.spec.js
  packages/@vue/cli-shared-utils/index.js
  packages/@vue/cli-shared-utils/lib/pluginOrder.js
  packages/@vue/cli/__tests__/Generator.spec.js
  packages/@vue/cli/lib/Creator.js
  packages/@vue/cli/lib/Generator.js
Labels: PR: New Feature

#6519 chore: use scoped package names for aliases
  packages/@vue/cli-service/lib/commands/build/resolveWcEntry.js
  packages/@vue/cli-service/lib/config/base.js
  packages/@vue/cli-service/lib/config/vue-loader-v15-resolve-compat/vue-loader.js
  packages/@vue/cli-service/package.json
  yarn.lock
Labels: PR: Internal

#6518 fix(pwa): Replace closeTag parameter with voidTag for HtmlWebpackPlugin
  packages/@vue/cli-plugin-pwa/lib/HtmlPwaPlugin.js
Labels: PR: Bug Fix

#6530 feat(cli-service): add support new image format avif
  packages/@vue/cli-service/lib/config/assets.js
Labels: PR: New Feature
