Repository vuejs/vue-cli, pull requests merged in 2021-01, with the labels that each got.

#6162 fix(cli-service): restrict request headers of historyApiFallback in WebpackDevServer
  packages/@vue/cli-service/lib/commands/serve.js
Labels: PR: Bug Fix

#6185 docs(zh): fix `publicPath` hash
  docs/zh/config/README.md
Labels: PR: Documentation

#6186 fix(mocha): workaround the ShadowRoot issue in Vue 3.0.5
  packages/@vue/cli-plugin-unit-mocha/setup.js
Labels: PR: Bug Fix

#5327 fix pwa installability when using noopServiceWorker "Page does not work offline"
  packages/@vue/cli-plugin-pwa/lib/noopServiceWorker.js
Labels: PR: Bug Fix

#6001 feat: open browser when toast clicked
  packages/@vue/cli-ui/apollo-server/util/notification.js
  packages/@vue/cli/lib/ui.js
Labels: PR: New Feature

#6187 feat!: bump default sass-loader version to v10, drop sass-loader v7 support
  docs/migrations/migrate-from-v4.md
  packages/@vue/cli-service/__tests__/css.spec.js
  packages/@vue/cli-service/generator/index.js
  packages/@vue/cli-service/lib/config/css.js
  packages/@vue/cli-service/package.json
  yarn.lock
Labels: PR: Breaking Change, PR: New Feature

#6192 fix: should use graphql v15 at all levels of dependency
  package.json
  packages/@vue/cli-ui/package.json
  yarn.lock
Labels: PR: Bug Fix

#6215 fix(unit-mocha): shouldn't require webpack-4 plugin with cli-service v4
  packages/@vue/cli-plugin-unit-mocha/generator/index.js
Labels: PR: Bug Fix

#6189 refactor: fix eslint warnings in the cli-ui codebase
  packages/@vue/cli-ui/src/components/content/TerminalView.vue
  packages/@vue/cli-ui/src/components/dashboard/Widget.vue
  packages/@vue/cli-ui/src/components/dashboard/WidgetAddPane.vue
  packages/@vue/cli-ui/src/components/file-diff/FileDiffChange.vue
  packages/@vue/cli-ui/src/components/folder/FolderExplorer.vue
  packages/@vue/cli-ui/src/components/prompt/PromptsList.vue
  packages/@vue/cli-ui/src/components/view/ViewNav.vue
  packages/@vue/cli-ui/src/components/view/ViewNavButton.vue
Labels: PR: Internal

#6198 Support svg favicon
  packages/@vue/cli-plugin-pwa/README.md
  packages/@vue/cli-plugin-pwa/lib/HtmlPwaPlugin.js
Labels: PR: New Feature

#6218 fix: "commonjs2" target should not be used with "output.library"
  packages/@vue/cli-service/lib/commands/build/resolveLibConfig.js
Labels: PR: Bug Fix

#6222 chore: disable cacheCompression for babel-loader by default
  packages/@vue/cli-plugin-babel/index.js
Labels: PR: Internal

#6224 fix: discard `NODE_ENV` when installing project dependencies
  packages/@vue/cli/lib/util/ProjectPackageManager.js
Labels: PR: Bug Fix

#5794 fix(cli): resolve plugins relative to the package context
  packages/@vue/cli-service/lib/Service.js
  packages/@vue/cli-shared-utils/lib/module.js
Labels: PR: Bug Fix

#6235 feat(typescript): add `useDefineForClassFields` option in tsconfig template
  packages/@vue/cli-plugin-typescript/generator/template/tsconfig.json
Labels: PR: New Feature

#6221 fix(cli-service): avoiding recreating dist directory
  docs/config/README.md
  docs/guide/cli-service.md
  docs/zh/config/README.md
  docs/zh/guide/cli-service.md
  packages/@vue/cli-service/lib/commands/build/index.js
Labels: PR: Bug Fix

#6237 fix code demo
  docs/zh/dev-guide/plugin-dev.md
Labels: PR: Documentation

#6242 chore: upgrade commander to v7
  packages/@vue/cli/bin/vue.js
  packages/@vue/cli/lib/migrate.js
  packages/@vue/cli/package.json
  yarn.lock
Labels: PR: Internal

#6230 fix: mini-css-extract-plugin publicPath option can be an absolute path
  packages/@vue/cli-service/lib/config/css.js
Labels: PR: Bug Fix

#6239 Update deployment.md
  docs/guide/deployment.md
Labels: PR: Documentation
