Repository vuejs/vue-cli, pull requests merged in 2022-02, with the labels that each got.

#6520 feat: Upgraded Nightwatch to 2.0, updated distribued config
  packages/@vue/cli-plugin-e2e-nightwatch/__tests__/nightwatchPlugin.spec.js
  packages/@vue/cli-plugin-e2e-nightwatch/index.js
  packages/@vue/cli-plugin-e2e-nightwatch/nightwatch.conf.js
  packages/@vue/cli-plugin-e2e-nightwatch/nightwatch.config.js
  packages/@vue/cli-plugin-e2e-nightwatch/package.json
Labels: PR: Breaking Change, PR: New Feature

#6980 feat: add build stats hash support
  packages/@vue/cli-service/lib/commands/build/formatStats.js
Labels: PR: New Feature

#6985 feat!: make `cache-loader` optional
  packages/@vue/cli-plugin-typescript/index.js
  packages/@vue/cli-plugin-typescript/package.json
  packages/@vue/cli-service/lib/config/base.js
  packages/@vue/cli-service/package.json
Labels: PR: Breaking Change

#6972 Remove --skip-plugin from arguments
  docs/guide/cli-service.md
  packages/@vue/cli-service/__tests__/Service.spec.js
  packages/@vue/cli-service/lib/Service.js
Labels: PR: Bug Fix
